# Generated by Django 6.0.5 on 2026-05-11 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, verbose_name='Host')),
                ('port', models.PositiveSmallIntegerField(default=5432, verbose_name='Port')),
                ('dbname', models.CharField(max_length=100, verbose_name='Datenbank')),
                ('user', models.CharField(max_length=100, verbose_name='Benutzername')),
                ('password', models.CharField(max_length=100, verbose_name='Passwort')),
            ],
            options={
                'verbose_name': 'Datenbankverbindung',
                'verbose_name_plural': 'Datenbankverbindungen',
                'db_table': 'pygeoapi_database_connection',
                'ordering': ['host', 'dbname', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('deactivated', models.BooleanField(verbose_name='deaktiviert')),
                ('service_id', models.BigIntegerField(unique=True)),
                ('schema', models.CharField(max_length=100, verbose_name='Name des Schemas')),
                ('table', models.CharField(max_length=100, verbose_name='Name der/des Tabelle/Views')),
                ('id_field', models.CharField(max_length=100, verbose_name='Name des ID-Attributs')),
                ('title_field', models.CharField(max_length=100, verbose_name='Name des Attributs mit (möglichst eindeutiger) Bezeichnung')),
                ('geom_field', models.CharField(max_length=100, verbose_name='Name des Geometrie-Attributs')),
                ('storage_crs', models.CharField(choices=[('https://www.opengis.net/def/crs/EPSG/0/25833', 'EPSG:25833'), ('https://www.opengis.net/def/crs/EPSG/0/4326', 'EPSG:4326'), ('https://www.opengis.net/def/crs/OGC/0/CRS84', 'CRS:84')], verbose_name='Koordinatenreferenzsystem der Geometrie')),
                ('database_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_database_connections', to='pygeoapi.databaseconnection', verbose_name='Datenbankverbindung')),
            ],
            options={
                'verbose_name': 'Kollektion',
                'verbose_name_plural': 'Kollektionen',
                'db_table': 'pygeoapi_collection',
                'ordering': ['service_id'],
            },
        ),
    ]
