# Generated by Django 5.2.3 on 2026-01-20 15:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255, verbose_name='Host')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('dbname', models.CharField(max_length=1024, verbose_name='Datenbank')),
                ('user', models.CharField(max_length=1024, verbose_name='Username')),
                ('password', models.CharField(max_length=1024, verbose_name='Passwort')),
            ],
            options={
                'verbose_name': 'Datenbankverbindung',
                'verbose_name_plural': 'Datenbankverbindungen',
                'db_table': 'pygeoapi_database_connection',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.CharField(max_length=1024, verbose_name='Beschreibung')),
                ('schema', models.CharField(max_length=255, verbose_name='Datenbank Schema')),
                ('table', models.CharField(max_length=255, verbose_name='Datenbank Tabelle')),
                ('id_field', models.CharField(max_length=255, verbose_name='ID Feld')),
                ('geometry_field', models.CharField(max_length=255, verbose_name='Geometrie Feld')),
                ('storage_crs', models.CharField(max_length=255, verbose_name='EPSG-Code des Koordinatenreferenzsystems')),
                ('bbox_north', models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('-90'), 'Der Wert für Norden (räumliche Ausdehnung) muss mindestens -90 sein.'), django.core.validators.MaxValueValidator(Decimal('90'), 'Der Wert für Norden (räumliche Ausdehnung) darf höchstens 90 sein.')], verbose_name='Kartenbereich (Nord)')),
                ('bbox_east', models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('-180'), 'Der Wert für Osten (räumliche Ausdehnung) muss mindestens -180 sein.'), django.core.validators.MaxValueValidator(Decimal('180'), 'Der Wert für Osten (räumliche Ausdehnung) darf höchstens 180 sein.')], verbose_name='Kartenbereich (Ost)')),
                ('bbox_south', models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('-90'), 'Der Wert für Süden (räumliche Ausdehnung) muss mindestens -90 sein.'), django.core.validators.MaxValueValidator(Decimal('90'), 'Der Wert für Süden (räumliche Ausdehnung) darf höchstens 90 sein.')], verbose_name='Kartenbereich (Süd)')),
                ('bbox_west', models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('-180'), 'Der Wert für Westen (räumliche Ausdehnung) muss mindestens -180 sein.'), django.core.validators.MaxValueValidator(Decimal('180'), 'Der Wert für Westen (räumliche Ausdehnung) darf höchstens 180 sein.')], verbose_name='Kartenbereich (West)')),
                ('deactivated', models.BooleanField(verbose_name='deaktiviert')),
                ('model', models.OneToOneField(limit_choices_to={'app_label': 'datenmanagement'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('database_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pygeoapi.databaseconnection')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'db_table': 'pygeoapi_collection',
            },
        ),
        migrations.CreateModel(
            name='CollectionCrs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crs', models.CharField(max_length=255, verbose_name='EPSG-Code')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pygeoapi.collection')),
            ],
            options={
                'verbose_name': 'Collection Crs',
                'verbose_name_plural': 'Collection Crs',
                'db_table': 'pygeoapi_collection_crs',
            },
        ),
        migrations.CreateModel(
            name='CollectionKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255, verbose_name='Keyword')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pygeoapi.collection')),
            ],
            options={
                'verbose_name': 'Collection Keyword',
                'verbose_name_plural': 'Collection Keywords',
                'db_table': 'pygeoapi_collection_keyword',
            },
        ),
    ]
