# Generated by Django 6.0.7 on 2026-08-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygeoapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='Bezeichner (wie im Identity Provider)')),
                ('label', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_children', to='pygeoapi.role', verbose_name='Eltern-Rolle')),
            ],
            options={
                'verbose_name': 'Rolle',
                'verbose_name_plural': 'Rollen',
                'db_table': 'pygeoapi_role',
                'ordering': ['identifier'],
                'constraints': [models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='pygeoapi_role_no_self_parent')],
            },
        ),
    ]
