# Generated by Django 6.0.4 on 2026-04-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pygeoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name'], 'verbose_name': 'Kollektion', 'verbose_name_plural': 'Kollektionen'},
        ),
        migrations.AlterModelOptions(
            name='databaseconnection',
            options={'ordering': ['host', 'dbname', 'user'], 'verbose_name': 'Datenbankverbindung', 'verbose_name_plural': 'Datenbankverbindungen'},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='model',
        ),
        migrations.AddField(
            model_name='collection',
            name='service',
            field=models.OneToOneField(default=204, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Service aus GDI.HRO Metadata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='database_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pygeoapi.databaseconnection', verbose_name='Datenbankverbindung'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='dbname',
            field=models.CharField(max_length=100, verbose_name='Datenbank'),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='host',
            field=models.CharField(max_length=100, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Passwort'),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='port',
            field=models.PositiveSmallIntegerField(default=5432, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Benutzername'),
        ),
    ]
