# Generated by Django 6.0.4 on 2026-04-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygeoapi', '0002_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='database_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_database_connections', to='pygeoapi.databaseconnection', verbose_name='Datenbankverbindung'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='service',
            field=models.BigIntegerField(unique=True, verbose_name='Service aus GDI.HRO Metadata'),
        ),
    ]
