# Generated by Django 6.0.7 on 2026-08-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygeoapi', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAttribute',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name des Attributs')),
                ('is_present', models.BooleanField(default=True, verbose_name='in der Quelle vorhanden')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pygeoapi.collection', verbose_name='Kollektion')),
            ],
            options={
                'verbose_name': 'Attribut einer Kollektion',
                'verbose_name_plural': 'Attribute einer Kollektion',
                'db_table': 'pygeoapi_collection_attribute',
                'ordering': ['collection', 'name'],
                'constraints': [models.UniqueConstraint(fields=('collection', 'name'), name='pygeoapi_collection_attribute_unique_name_per_collection')],
            },
        ),
    ]
