# Generated by Django 6.0.4 on 2026-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygeoapi', '0003_alter_collection_database_connection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='service',
        ),
        migrations.AddField(
            model_name='collection',
            name='service_id',
            field=models.BigIntegerField(default=700, unique=True),
            preserve_default=False,
        ),
    ]
