# Generated by Django 6.0.7 on 2026-08-07 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygeoapi', '0003_collectionattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeReadPermission',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_permissions', to='pygeoapi.collectionattribute', verbose_name='Attribut')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_permissions', to='pygeoapi.role', verbose_name='Rolle')),
            ],
            options={
                'verbose_name': 'Leserecht an einem Attribut',
                'verbose_name_plural': 'Leserechte an Attributen',
                'db_table': 'pygeoapi_attribute_read_permission',
                'ordering': ['role', 'attribute'],
                'constraints': [models.UniqueConstraint(fields=('role', 'attribute'), name='pygeoapi_attribute_read_permission_unique_role_attribute')],
            },
        ),
    ]
