# Generated by Django 6.0.7 on 2026-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pygeoapi', '0004_attributereadpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionattribute',
            name='data_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Datentyp in der Quelle'),
        ),
    ]
