# Generated by Django 5.2.1 on 2025-06-17 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Massnahme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Massnahme',
                'verbose_name_plural': ('Massnahmen',),
                'db_table': 'd3_massnahme',
            },
        ),
        migrations.CreateModel(
            name='Metadaten',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255, unique=True, verbose_name='Titel')),
                ('gui_element', models.CharField(choices=[('select', 'Select'), ('input_text', 'Input-Text'), ('input_zahl', 'Input-Zahl'), ('checkbox', 'Checkbox')], max_length=45, verbose_name='GUI Element')),
                ('erforderlich', models.BooleanField(default=False, null=True, verbose_name='Eingabe erforderlich?')),
                ('regex', models.CharField(blank=True, max_length=255, null=True, verbose_name='Validierung über Regex')),
                ('d3_id', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Metadaten',
                'verbose_name_plural': ('Metadaten',),
                'db_table': 'd3_metadaten',
            },
        ),
        migrations.CreateModel(
            name='Verfahren',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Verfahren',
                'verbose_name_plural': ('Verfahren',),
                'db_table': 'd3_verfahren',
            },
        ),
        migrations.CreateModel(
            name='Akte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('d3_id', models.CharField(max_length=32)),
                ('object_id', models.CharField(max_length=14)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Akte',
                'verbose_name_plural': ('Akten',),
                'db_table': 'd3_akte',
            },
        ),
        migrations.CreateModel(
            name='AktenOrdner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('d3_id', models.CharField(max_length=32)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'AktenOrdner',
                'verbose_name_plural': ('AktenOrdner',),
                'db_table': 'd3_akten_ordner',
            },
        ),
        migrations.CreateModel(
            name='Vorgang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=255)),
                ('d3_id', models.CharField(max_length=32)),
                ('vorgangs_typ', models.CharField(max_length=50)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert', models.DateTimeField(auto_now=True)),
                ('akten_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3.akte')),
                ('erstellt_durch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Vorgang',
                'verbose_name_plural': 'Vorgänge',
                'db_table': 'd3_vorgang',
            },
        ),
        migrations.CreateModel(
            name='VorgangMetadaten',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wert', models.CharField(max_length=255)),
                ('aktualisiert', models.DateField(auto_now=True)),
                ('erstellt', models.DateField(auto_now_add=True)),
                ('erstellt_durch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('metadaten_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3.metadaten')),
                ('vorgang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3.vorgang')),
            ],
            options={
                'verbose_name': 'VorgangMetadaten',
                'verbose_name_plural': ('VorgangMetadaten',),
                'db_table': 'd3_vorgang_metadaten',
            },
        ),
    ]
