# Generated by Django 5.2.1 on 2025-06-26 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akte',
            options={'verbose_name': 'Akte', 'verbose_name_plural': 'Akten'},
        ),
        migrations.AlterModelOptions(
            name='aktenordner',
            options={'verbose_name': 'Akten Ordner', 'verbose_name_plural': 'Akten Ordner'},
        ),
        migrations.AlterModelOptions(
            name='massnahme',
            options={'verbose_name': 'Massnahme', 'verbose_name_plural': 'Massnahmen'},
        ),
        migrations.AlterModelOptions(
            name='metadaten',
            options={'verbose_name': 'Metadaten', 'verbose_name_plural': 'Metadaten'},
        ),
        migrations.AlterModelOptions(
            name='verfahren',
            options={'verbose_name': 'Verfahren', 'verbose_name_plural': 'Verfahren'},
        ),
        migrations.AlterModelOptions(
            name='vorgangmetadaten',
            options={'verbose_name': 'VorgangMetadaten', 'verbose_name_plural': 'VorgangMetadaten'},
        ),
        migrations.AlterField(
            model_name='vorgang',
            name='erstellt_durch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vorgangmetadaten',
            name='erstellt_durch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
