# Generated by Django 5.2.1 on 2025-07-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3', '0002_alter_akte_options_alter_aktenordner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadatenOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255, verbose_name='Wert')),
                ('metadaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3.metadaten')),
            ],
            options={
                'verbose_name': 'Metadatenoption',
                'verbose_name_plural': 'Metadatenoption',
                'db_table': 'd3_metadaten_option',
            },
        ),
        migrations.CreateModel(
            name='DokumentMetadatenProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Metadaten (Dokument)',
                'verbose_name_plural': 'Metadaten (Dokument)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('d3.metadaten',),
        ),
        migrations.CreateModel(
            name='VorgangMetadatenProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Metadaten (Vorgang)',
                'verbose_name_plural': 'Metadaten (Vorgang)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('d3.metadaten',),
        ),
        migrations.AddField(
            model_name='metadaten',
            name='category',
            field=models.CharField(default='vorgang', max_length=50),
        ),
    ]
