# Generated by Django 5.2.1 on 2025-07-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3', '0003_dateimetadaten_metadaten_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadaten',
            name='titel',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
    ]
