# Generated by Django 5.2.3 on 2025-07-31 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3', '0004_alter_metadaten_titel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktenordner',
            name='d3_id',
        ),
        migrations.CreateModel(
            name='AktenOrdnerOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('d3_id', models.CharField(max_length=36)),
                ('wert', models.CharField(blank=True, max_length=255, null=True)),
                ('ist_namens_feld', models.BooleanField(default=False)),
                ('akten_ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3.aktenordner')),
            ],
            options={
                'verbose_name': 'Akten Ordner Option',
                'verbose_name_plural': 'Akten Ordner Optionen',
                'db_table': 'd3_akten_ordner_option',
            },
        ),
    ]
