# Generated by Django 5.2.7 on 2025-10-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('d3', '0005_remove_aktenordner_d3_id_aktenordneroption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktenordner',
            options={'verbose_name': 'Aktenordner', 'verbose_name_plural': 'Aktenordner'},
        ),
        migrations.AlterModelOptions(
            name='aktenordneroption',
            options={'verbose_name': 'Aktenordner-Option', 'verbose_name_plural': 'Aktenordner-Optionen'},
        ),
        migrations.AlterModelOptions(
            name='dokumentmetadatenproxy',
            options={'verbose_name': 'Metadatum (Dokument)', 'verbose_name_plural': 'Metadaten (Dokument)'},
        ),
        migrations.AlterModelOptions(
            name='massnahme',
            options={'verbose_name': 'Maßnahme', 'verbose_name_plural': 'Maßnahmen'},
        ),
        migrations.AlterModelOptions(
            name='metadaten',
            options={'verbose_name': 'Metadaten', 'verbose_name_plural': 'Metadatum'},
        ),
        migrations.AlterModelOptions(
            name='metadatenoption',
            options={'verbose_name': 'Metadatenoption', 'verbose_name_plural': 'Metadatenoptionen'},
        ),
        migrations.AlterModelOptions(
            name='vorgangmetadaten',
            options={'verbose_name': 'Vorgang-Metadaten', 'verbose_name_plural': 'Vorgänge-Metadaten'},
        ),
        migrations.AlterModelOptions(
            name='vorgangmetadatenproxy',
            options={'verbose_name': 'Metadatum (Vorgang)', 'verbose_name_plural': 'Metadaten (Vorgang)'},
        ),
        migrations.AlterField(
            model_name='akte',
            name='d3_id',
            field=models.CharField(max_length=36, verbose_name='d.3-ID'),
        ),
        migrations.AlterField(
            model_name='akte',
            name='model',
            field=models.ForeignKey(limit_choices_to={'app_label': 'datenmanagement'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Datenmodell'),
        ),
        migrations.AlterField(
            model_name='akte',
            name='object_id',
            field=models.CharField(max_length=36, verbose_name='Objekt-ID'),
        ),
        migrations.AlterField(
            model_name='metadaten',
            name='category',
            field=models.CharField(default='vorgang', max_length=50, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='metadaten',
            name='gui_element',
            field=models.CharField(choices=[('select', 'Select'), ('input_text', 'Input-Text'), ('input_zahl', 'Input-Zahl'), ('checkbox', 'Checkbox')], max_length=45, verbose_name='GUI-Element'),
        ),
        migrations.AlterField(
            model_name='metadaten',
            name='regex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Validierung via Regex'),
        ),
    ]
