# Generated by Django 5.2.8 on 2025-11-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3', '0006_alter_aktenordner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktenordneroption',
            name='ist_namens_feld',
            field=models.BooleanField(default=False, verbose_name='ist Namensfeld?'),
        ),
        migrations.AlterField(
            model_name='metadaten',
            name='category',
            field=models.CharField(default='vorgang', editable=False, max_length=50, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='metadaten',
            name='regex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RegExp zur Validierung'),
        ),
        migrations.AlterField(
            model_name='vorgang',
            name='vorgangs_typ',
            field=models.CharField(max_length=50, verbose_name='Vorgangstyp'),
        ),
    ]
