# Generated by Django 6.0.3 on 2026-03-31 05:47

import angebotsdb.models.base
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                (
                    "law_book",
                    models.CharField(
                        max_length=25,
                        verbose_name="Gesetzesbuch (Abkürzung, z.B. SGB VIII)",
                    ),
                ),
                (
                    "paragraph",
                    models.CharField(
                        max_length=25, verbose_name="Paragraph (ohne §, z.B. 8a)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gesetz",
                "verbose_name_plural": "Gesetze",
                "db_table": "law",
                "ordering": ["law_book", "paragraph"],
            },
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Bezeichnung"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
            ],
            options={
                "verbose_name": "Organisationseinheit",
                "verbose_name_plural": "Organisationseinheiten",
                "db_table": "angebotsdb_organisational_unit",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Bezeichnung")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="angebotsdb/hosts/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ansprechpartner",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="E-Mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Telefonnummer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Träger",
                "verbose_name_plural": "Träger",
                "db_table": "host",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                (
                    "service_type",
                    models.CharField(max_length=100, verbose_name="Angebotstyp"),
                ),
                ("service_id", models.IntegerField(verbose_name="Service-ID")),
                (
                    "image",
                    models.ImageField(
                        upload_to="angebotsdb/services/", verbose_name="Bild"
                    ),
                ),
                (
                    "position",
                    models.IntegerField(default=0, verbose_name="Reihenfolge"),
                ),
            ],
            options={
                "verbose_name": "Service-Bild",
                "verbose_name_plural": "Service-Bilder",
                "db_table": "service_image",
                "ordering": ["position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Bezeichnung"
                    ),
                ),
            ],
            options={
                "verbose_name": "Schlagwort",
                "verbose_name_plural": "Schlagworte",
                "db_table": "tag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TargetGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Zielgruppe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zielgruppe",
                "verbose_name_plural": "Zielgruppen",
                "db_table": "target_group",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Bezeichnung")),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
                "db_table": "topic",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                (
                    "service_type",
                    models.CharField(max_length=100, verbose_name="Angebotstyp"),
                ),
                ("service_id", models.IntegerField(verbose_name="Service-ID")),
                (
                    "created_by_user_id",
                    models.IntegerField(verbose_name="Erstellt von (User-ID)"),
                ),
                (
                    "reviewed_by_user_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Geprüft von (User-ID)"
                    ),
                ),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("pending", "Offen"),
                            ("approved", "Freigegeben"),
                            ("rejected", "Zurückgewiesen"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Task-Status",
                    ),
                ),
                (
                    "comments",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Feld-Kommentare"
                    ),
                ),
                (
                    "approved_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Freigegebener Snapshot"
                    ),
                ),
                (
                    "submitted_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Eingereichter Snapshot"
                    ),
                ),
                (
                    "assigned_org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_tasks",
                        to="angebotsdb.orgunit",
                        verbose_name="Zuständige OE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prüfauftrag",
                "verbose_name_plural": "Prüfaufträge",
                "db_table": "review_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InboxMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("review_request", "Prüfauftrag"),
                            ("revision_request", "Überarbeitungsauftrag"),
                        ],
                        max_length=30,
                        verbose_name="Nachrichtentyp",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Gelesen")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Erledigt"),
                ),
                (
                    "target_org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_messages",
                        to="angebotsdb.orgunit",
                        verbose_name="Empfänger-OE",
                    ),
                ),
                (
                    "target_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_messages",
                        to="angebotsdb.provider",
                        verbose_name="Empfänger-Einrichtung",
                    ),
                ),
                (
                    "review_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_messages",
                        to="angebotsdb.reviewtask",
                        verbose_name="Prüfauftrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inbox-Nachricht",
                "verbose_name_plural": "Inbox-Nachrichten",
                "db_table": "inbox_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        default="POINT(0 0)", srid=25833, verbose_name="Geometrie"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=150, verbose_name="Straße und Hausnummer"
                    ),
                ),
                ("zip", models.IntegerField(verbose_name="PLZ")),
                ("city", models.CharField(max_length=100, verbose_name="Gemeinde")),
                (
                    "contact_hours",
                    models.TextField(
                        blank=True,
                        help_text="z.B. Mo Di Mi 7:30 - 15:00 Uhr, Do 8:00 - 13:00 Uhr",
                        null=True,
                        verbose_name="Kontaktzeiträume",
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="E-Mail")),
                (
                    "expiry_date",
                    models.DateField(
                        help_text="Datum, an dem das Angebot ausläuft.",
                        verbose_name="Ablaufdatum",
                    ),
                ),
                (
                    "info_url",
                    models.URLField(
                        blank=True,
                        help_text="Externe URL für weitere Informationen (z.B. Träger-Website).",
                        max_length=500,
                        null=True,
                        verbose_name="Weiterführender Link",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("in_review", "In Prüfung"),
                            ("revision_needed", "Überarbeitung nötig"),
                            ("published", "Veröffentlicht"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("setting", models.TextField(verbose_name="Beratungssetting")),
                (
                    "application_needed",
                    models.BooleanField(verbose_name="Antrag erforderlich?"),
                ),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Telefonnummer"),
                ),
                ("costs", models.FloatField(verbose_name="Kosten in Euro")),
                (
                    "catchment_area_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste von PyGeoAPI-Endpunkt-URIs. Für jeden Stadtteil im Einzugsgebiet wird die entsprechende Endpunkt-URI gespeichert.",
                        verbose_name="Einzugsgebiet",
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zeigt auf den originalen published-Datensatz, von dem diese Draft-Copy abgeleitet wurde. Null bei normalen Services.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_copies",
                        to="angebotsdb.familyservice",
                        verbose_name="Veröffentlichte Version",
                    ),
                ),
                (
                    "legal_basis",
                    models.ManyToManyField(
                        related_name="%(class)s",
                        to="angebotsdb.law",
                        verbose_name="Gesetzliche Grundlage",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="angebotsdb.provider",
                        verbose_name="Anbieter",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s",
                        to="angebotsdb.tag",
                        verbose_name="Schlagworte",
                    ),
                ),
                (
                    "target_group",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s",
                        to="angebotsdb.targetgroup",
                        verbose_name="Zielgruppe(n)",
                    ),
                ),
                (
                    "topic",
                    models.ManyToManyField(
                        related_name="%(class)s",
                        to="angebotsdb.topic",
                        verbose_name="Kategorie(n)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Angebot für Familien",
                "verbose_name_plural": "Angebote für Familien",
            },
        ),
        migrations.CreateModel(
            name="ChildrenAndYouthService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        default="POINT(0 0)", srid=25833, verbose_name="Geometrie"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=150, verbose_name="Straße und Hausnummer"
                    ),
                ),
                ("zip", models.IntegerField(verbose_name="PLZ")),
                ("city", models.CharField(max_length=100, verbose_name="Gemeinde")),
                (
                    "contact_hours",
                    models.TextField(
                        blank=True,
                        help_text="z.B. Mo Di Mi 7:30 - 15:00 Uhr, Do 8:00 - 13:00 Uhr",
                        null=True,
                        verbose_name="Kontaktzeiträume",
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="E-Mail")),
                (
                    "expiry_date",
                    models.DateField(
                        help_text="Datum, an dem das Angebot ausläuft.",
                        verbose_name="Ablaufdatum",
                    ),
                ),
                (
                    "info_url",
                    models.URLField(
                        blank=True,
                        help_text="Externe URL für weitere Informationen (z.B. Träger-Website).",
                        max_length=500,
                        null=True,
                        verbose_name="Weiterführender Link",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("in_review", "In Prüfung"),
                            ("revision_needed", "Überarbeitung nötig"),
                            ("published", "Veröffentlicht"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "setting",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beratungssetting"
                    ),
                ),
                (
                    "application_needed",
                    models.BooleanField(verbose_name="Antrag erforderlich?"),
                ),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Telefonnummer"),
                ),
                ("costs", models.FloatField(verbose_name="Kosten in Euro")),
                (
                    "catchment_area_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste von PyGeoAPI-Endpunkt-URIs. Für jeden Stadtteil im Einzugsgebiet wird die entsprechende Endpunkt-URI gespeichert.",
                        verbose_name="Einzugsgebiet",
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zeigt auf den originalen published-Datensatz, von dem diese Draft-Copy abgeleitet wurde. Null bei normalen Services.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_copies",
                        to="angebotsdb.childrenandyouthservice",
                        verbose_name="Veröffentlichte Version",
                    ),
                ),
                (
                    "legal_basis",
                    models.ManyToManyField(
                        related_name="%(class)s",
                        to="angebotsdb.law",
                        verbose_name="Gesetzliche Grundlage",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="angebotsdb.provider",
                        verbose_name="Anbieter",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s",
                        to="angebotsdb.tag",
                        verbose_name="Schlagworte",
                    ),
                ),
                (
                    "target_group",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s",
                        to="angebotsdb.targetgroup",
                        verbose_name="Zielgruppe(n)",
                    ),
                ),
                (
                    "topic",
                    models.ManyToManyField(
                        related_name="%(class)s",
                        to="angebotsdb.topic",
                        verbose_name="Kategorie(n)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Angebot für Kinder und Jugendliche",
                "verbose_name_plural": "Angebote für Kinder und Jugendliche",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        help_text="ID des Django Users",
                        unique=True,
                        verbose_name="Benutzer-ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                (
                    "organisational_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="OE für Verwaltungsnutzer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_users",
                        to="angebotsdb.orgunit",
                        verbose_name="Organisationseinheit",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Träger für Einrichtungsnutzer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facility_users",
                        to="angebotsdb.provider",
                        verbose_name="Träger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benutzerprofil",
                "verbose_name_plural": "Benutzerprofile",
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="WoftGService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        default="POINT(0 0)", srid=25833, verbose_name="Geometrie"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=150, verbose_name="Straße und Hausnummer"
                    ),
                ),
                ("zip", models.IntegerField(verbose_name="PLZ")),
                ("city", models.CharField(max_length=100, verbose_name="Gemeinde")),
                (
                    "contact_hours",
                    models.TextField(
                        blank=True,
                        help_text="z.B. Mo Di Mi 7:30 - 15:00 Uhr, Do 8:00 - 13:00 Uhr",
                        null=True,
                        verbose_name="Kontaktzeiträume",
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="E-Mail")),
                (
                    "expiry_date",
                    models.DateField(
                        help_text="Datum, an dem das Angebot ausläuft.",
                        verbose_name="Ablaufdatum",
                    ),
                ),
                (
                    "info_url",
                    models.URLField(
                        blank=True,
                        help_text="Externe URL für weitere Informationen (z.B. Träger-Website).",
                        max_length=500,
                        null=True,
                        verbose_name="Weiterführender Link",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("in_review", "In Prüfung"),
                            ("revision_needed", "Überarbeitung nötig"),
                            ("published", "Veröffentlicht"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("setting", models.TextField(verbose_name="Beratungssetting")),
                (
                    "application_needed",
                    models.BooleanField(verbose_name="Antrag erforderlich?"),
                ),
                (
                    "phone",
                    models.CharField(max_length=255, verbose_name="Telefonnummer"),
                ),
                ("costs", models.FloatField(verbose_name="Kosten in Euro")),
                (
                    "handicap_accessible",
                    models.BooleanField(verbose_name="Barrierefreier Zugang?"),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="angebotsdb.provider",
                        verbose_name="Anbieter",
                    ),
                ),
                (
                    "legal_basis",
                    models.ManyToManyField(
                        related_name="%(class)s",
                        to="angebotsdb.law",
                        verbose_name="Gesetzliche Grundlage",
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zeigt auf den originalen published-Datensatz, von dem diese Draft-Copy abgeleitet wurde. Null bei normalen Services.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_copies",
                        to="angebotsdb.woftgservice",
                        verbose_name="Veröffentlichte Version",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s",
                        to="angebotsdb.tag",
                        verbose_name="Schlagworte",
                    ),
                ),
                (
                    "target_group",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)s",
                        to="angebotsdb.targetgroup",
                        verbose_name="Zielgruppe(n)",
                    ),
                ),
                (
                    "topic",
                    models.ManyToManyField(
                        related_name="%(class)s",
                        to="angebotsdb.topic",
                        verbose_name="Kategorie(n)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Angebot im Rahmen des WoftG",
                "verbose_name_plural": "Angebote im Rahmen des WoftG",
            },
        ),
        migrations.CreateModel(
            name="OrgUnitServicePermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=angebotsdb.models.base.get_service_type_choices,
                        max_length=100,
                        verbose_name="Angebotstyp",
                    ),
                ),
                (
                    "organisational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_permissions",
                        to="angebotsdb.orgunit",
                        verbose_name="Organisationseinheit",
                    ),
                ),
            ],
            options={
                "verbose_name": "OrgUnit-Service-Berechtigung",
                "verbose_name_plural": "OrgUnit-Service-Berechtigungen",
                "db_table": "angebotsdb_org_unit_service_permission",
                "unique_together": {("organisational_unit", "service_type")},
            },
        ),
    ]
