# Generated by Django 6.0.3 on 2026-04-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orgunitservicepermission",
            options={
                "verbose_name": "OE-Angebot-Berechtigung",
                "verbose_name_plural": "OE-Angebot-Berechtigungen",
            },
        ),
        migrations.AlterModelTable(
            name="provider",
            table="provider",
        ),
    ]
