# Generated by Django 6.0.3 on 2026-04-28 08:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0002_alter_orgunitservicepermission_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="address",
        ),
        migrations.AddField(
            model_name="provider",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Gemeinde"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=25833, verbose_name="Geometrie"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="street",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Straße und Hausnummer",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="zip",
            field=models.IntegerField(blank=True, null=True, verbose_name="PLZ"),
        ),
    ]
