# Generated by Django 6.0.3 on 2026-05-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0003_remove_provider_address_provider_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewtask",
            name="assigned_org_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_tasks",
                to="angebotsdb.orgunit",
                verbose_name="Zuständige OE",
            ),
        ),
    ]
