# Generated by Django 6.0.3 on 2026-07-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0004_alter_reviewtask_assigned_org_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childrenandyouthservice",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="woftgservice",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="familyservice",
            name="tags",
        ),
        migrations.AlterField(
            model_name="childrenandyouthservice",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="angebotsdb.provider",
                verbose_name="Träger",
            ),
        ),
        migrations.AlterField(
            model_name="familyservice",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="angebotsdb.provider",
                verbose_name="Träger",
            ),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="angebotsdb.provider",
                verbose_name="Träger",
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
