# Generated by Django 6.0.3 on 2026-07-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0005_remove_childrenandyouthservice_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_email_notifications",
            field=models.BooleanField(
                default=False,
                help_text="Bei neuen Nachrichten im Posteingang der Angebotsdatenbank per E-Mail benachrichtigen",
                verbose_name="E-Mail-Benachrichtigungen",
            ),
        ),
    ]
