# Generated by Django 6.0.3 on 2026-08-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0006_userprofile_receive_email_notifications"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChildrenAndYouthService",
            new_name="ChildrenYouthAndFamilyService",
        ),
        migrations.AlterModelOptions(
            name="childrenyouthandfamilyservice",
            options={
                "verbose_name": "Angebot für Kinder, Jugendliche und Familien",
                "verbose_name_plural": "Angebote für Kinder, Jugendliche und Familien",
            },
        ),
    ]
