# Generated by Django 6.0.3 on 2026-08-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0008_merge_familyservice_into_children_youth_and_family"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FamilyService",
        ),
    ]
