# Generated by Django 6.0.3 on 2026-08-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0009_delete_familyservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Bezeichnung"
                    ),
                ),
            ],
            options={
                "verbose_name": "Schlagwort",
                "verbose_name_plural": "Schlagworte",
                "db_table": "tag",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="childrenyouthandfamilyservice",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s",
                to="angebotsdb.tag",
                verbose_name="Schlagworte",
            ),
        ),
        migrations.AddField(
            model_name="woftgservice",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s",
                to="angebotsdb.tag",
                verbose_name="Schlagworte",
            ),
        ),
    ]
