# Generated by Django 6.1 on 2026-09-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0010_tag_childrenyouthandfamilyservice_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childrenyouthandfamilyservice",
            name="contact_hours",
            field=models.TextField(
                blank=True,
                help_text="Wie und wann kann man Sie erreichen? z. Bsp. nach Vereinbarung, ganztägig über den Anrufbeantworter…",
                null=True,
                verbose_name="Kontaktzeiträume",
            ),
        ),
        migrations.AlterField(
            model_name="childrenyouthandfamilyservice",
            name="setting",
            field=models.TextField(
                blank=True, null=True, verbose_name="Angebotsdurchführung"
            ),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="contact_hours",
            field=models.TextField(
                blank=True,
                help_text="Wie und wann kann man Sie erreichen? z. Bsp. nach Vereinbarung, ganztägig über den Anrufbeantworter…",
                null=True,
                verbose_name="Kontaktzeiträume",
            ),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="setting",
            field=models.TextField(verbose_name="Angebotsdurchführung"),
        ),
    ]
