# Generated by Django 6.1 on 2026-09-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0010_tag_childrenyouthandfamilyservice_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="childrenyouthandfamilyservice",
            name="handicap_accessible",
            field=models.BooleanField(
                default=False, verbose_name="Barrierefreier Zugang?"
            ),
            preserve_default=False,
        ),
    ]
