# Generated by Django 6.1 on 2026-09-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0011_childrenyouthandfamilyservice_handicap_accessible"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["name"],
                "verbose_name": "Lebenslage",
                "verbose_name_plural": "Lebenslagen",
            },
        ),
        migrations.AlterField(
            model_name="childrenyouthandfamilyservice",
            name="topic",
            field=models.ManyToManyField(
                related_name="%(class)s",
                to="angebotsdb.topic",
                verbose_name="Lebenslage(n)",
            ),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="topic",
            field=models.ManyToManyField(
                related_name="%(class)s",
                to="angebotsdb.topic",
                verbose_name="Lebenslage(n)",
            ),
        ),
    ]
