# Generated by Django 6.1 on 2026-09-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("angebotsdb", "0013_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childrenyouthandfamilyservice",
            name="target_group",
            field=models.ManyToManyField(
                related_name="%(class)s",
                to="angebotsdb.targetgroup",
                verbose_name="Zielgruppe(n)",
            ),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="target_group",
            field=models.ManyToManyField(
                related_name="%(class)s",
                to="angebotsdb.targetgroup",
                verbose_name="Zielgruppe(n)",
            ),
        ),
    ]
