# Generated by Django 6.1 on 2026-09-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "angebotsdb",
            "0014_alter_childrenyouthandfamilyservice_target_group_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="woftgservice",
            options={
                "verbose_name": "Angebot im Rahmen des WoftG M-V",
                "verbose_name_plural": "Angebote im Rahmen des WoftG M-V",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="receive_email_notifications",
            field=models.BooleanField(
                default=False,
                help_text="Bei neuen Nachrichten im Posteingang des Angebotsfinders Jugend & Soziales per E-Mail benachrichtigen",
                verbose_name="E-Mail-Benachrichtigungen",
            ),
        ),
    ]
