# Generated by Django 4.2.5 on 2023-09-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Erstellungszeitpunkt')),
                ('templatefile', models.FileField(upload_to='', verbose_name='tatsächliche Templatedatei')),
                ('name', models.TextField(default='noch nicht benannt', verbose_name='Name des Templates')),
                ('description', models.TextField(verbose_name='Kurzbeschreibung des Templates')),
            ],
            options={
                'verbose_name': 'Export-Vorlage',
                'verbose_name_plural': 'Export-Vorlagen',
            },
        ),
        migrations.CreateModel(
            name='SuitableFor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usedkeys', models.JSONField(blank=True, null=True, verbose_name='ins Template zu speisende Attribute')),
                ('sortby', models.JSONField(blank=True, null=True, verbose_name='Sortierung der Einträge')),
                ('bemerkungen', models.TextField(blank=True, null=True)),
                ('datenthema', models.ForeignKey(limit_choices_to={'app_label': 'datenmanagement'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolbox.pdftemplate')),
            ],
            options={
                'verbose_name': 'Vorlage-Datenthema-Verknüpfung',
                'verbose_name_plural': 'Vorlage-Datenthema-Verknüpfungen',
            },
        ),
        migrations.AddField(
            model_name='pdftemplate',
            name='suitedfor',
            field=models.ManyToManyField(through='toolbox.SuitableFor', to='contenttypes.contenttype', verbose_name='geeignet für Datenthemen'),
        ),
    ]
