# Generated by Django 4.2.6 on 2023-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_pdftemplate_suitablefor_pdftemplate_suitedfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftemplate',
            name='templatefile',
            field=models.FileField(upload_to='latex_templates/', verbose_name='tatsächliche Templatedatei'),
        ),
    ]
