#!/usr/bin/env sh

echo "Checking Django rules via djLint..."
djlint datenwerft/templates/*.html accounts/templates/accounts/log*.html accounts/templates/accounts/test.html angebotsdb/templates/angebotsdb/*.html antragsmanagement/templates/antragsmanagement/*.html bemas/templates/bemas/*.html datenmanagement/templates/datenmanagement/*.html fmm/templates/fmm/*.html pygeoapi/templates/admin/pygeoapi/*.html pygeoapi/templates/admin/pygeoapi/edit_inline/*.html stadtbereichskatalog/templates/stadtbereichskatalog/*.html
