#!/usr/bin/env sh

echo "Checking Django rules via djLint..."
djlint datenwerft/templates/*.html accounts/templates/accounts/log*.html accounts/templates/accounts/test.html bemas/templates/bemas/*.html datenmanagement/templates/datenmanagement/*.html
