#!/usr/bin/env sh

echo "Checking JavaScript rules via ESLint..."
node_modules/.bin/eslint "bemas/templates/bemas/*.html" "datenmanagement/static/datenmanagement/js/*.js" "datenmanagement/templates/datenmanagement/list.html" "datenmanagement/templates/datenmanagement/start.html"
