#!/usr/bin/env sh

echo "Checking JavaScript rules via ESLint..."
node_modules/.bin/eslint "antragsmanagement/templates/antragsmanagement/*.html" "bemas/static/bemas/js/*.js" "bemas/templates/bemas/*.html" "datenmanagement/static/datenmanagement/js/*.js" "datenmanagement/templates/datenmanagement/*.html"
