# Generated by Django 5.2.3 on 2025-10-07 13:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Bild')),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=25833, verbose_name='Geometrie')),
                ('email', models.EmailField(max_length=255, verbose_name='E-Mail')),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('logo', models.ImageField(upload_to='hosts/', verbose_name='Logo')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Ansprechpartner')),
                ('email', models.EmailField(max_length=255, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefonnummer')),
            ],
            options={
                'verbose_name': 'Anbietender',
                'verbose_name_plural': 'Anbietende',
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('law_book', models.CharField(max_length=25, verbose_name='Gesetzesbuch (Abkürzung, z.B. SGB VIII)')),
                ('paragraph', models.CharField(max_length=25, verbose_name='Paragraoh (ohne §, z.B. 8a)')),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='HolidayService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiju.service')),
                ('time', models.DateTimeField(verbose_name='Zeitpunkt')),
                ('maximum_participants', models.SmallIntegerField(verbose_name='max. Teilnehmende')),
                ('costs', models.FloatField(verbose_name='Teilnehmerbetrag in €')),
                ('meeting_point', models.CharField(max_length=255, verbose_name='Treffpunkt')),
            ],
            options={
                'verbose_name': 'Ferienangebot',
                'verbose_name_plural': 'Ferienangebote',
                'db_table': 'ferienangebote',
            },
            bases=('kiju.service',),
        ),
        migrations.AddField(
            model_name='service',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiju.host'),
        ),
        migrations.AddField(
            model_name='service',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiju.topic'),
        ),
        migrations.CreateModel(
            name='PreventionService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiju.service')),
                ('setting', models.TextField(verbose_name='Beratungssetting')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefonnummer')),
                ('costs', models.FloatField(verbose_name='Kosten in Euro')),
                ('application_needed', models.BooleanField(verbose_name='Antrag erforderlich?')),
                ('legal_basis', models.ManyToManyField(to='kiju.law', verbose_name='Gesetzliche Grundlage')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
            },
            bases=('kiju.service',),
        ),
    ]
