# Generated by Django 5.2.3 on 2025-07-18 11:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Bild')),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=25833, verbose_name='Geometrie')),
                ('email', models.EmailField(max_length=255, verbose_name='E-Mail')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('logo', models.ImageField(upload_to='hosts/', verbose_name='Logo')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Ansprechpartner')),
                ('email', models.EmailField(max_length=255, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefonnummer')),
            ],
            options={
                'verbose_name': 'Anbietender',
                'verbose_name_plural': 'Anbietende',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
            ],
        ),
        migrations.CreateModel(
            name='Angebot',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiju.service')),
                ('setting', models.TextField(verbose_name='Beratungssetting')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefonnummer')),
                ('legal_basis', models.CharField(max_length=255, verbose_name='Gesetzliche Grundlage')),
                ('costs', models.FloatField(verbose_name='Kosten in Euro')),
                ('application_needed', models.BooleanField(verbose_name='Antrag erforderlich?')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
            },
            bases=('kiju.service',),
        ),
        migrations.CreateModel(
            name='Ferienangebot',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiju.service')),
                ('time', models.DateTimeField(verbose_name='Zeitpunkt')),
                ('maximum_participants', models.SmallIntegerField(verbose_name='max. Teilnehmende')),
                ('costs', models.FloatField(verbose_name='Teilnehmerbetrag in €')),
                ('meeting_point', models.CharField(max_length=255, verbose_name='Treffpunkt')),
            ],
            options={
                'verbose_name': 'Ferienangebot',
                'verbose_name_plural': 'Ferienangebote',
                'db_table': 'ferienangebote',
            },
            bases=('kiju.service',),
        ),
        migrations.AddField(
            model_name='service',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiju.host'),
        ),
        migrations.AddField(
            model_name='service',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiju.topic'),
        ),
    ]
