# Generated by Django 6.0.2 on 2026-02-24 13:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import kiju.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('law_book', models.CharField(max_length=25, verbose_name='Gesetzesbuch (Abkürzung, z.B. SGB VIII)')),
                ('paragraph', models.CharField(max_length=25, verbose_name='Paragraph (ohne §, z.B. 8a)')),
            ],
            options={
                'verbose_name': 'Gesetz',
                'verbose_name_plural': 'Gesetze',
                'db_table': 'law',
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
            ],
            options={
                'verbose_name': 'Organisationseinheit',
                'verbose_name_plural': 'Organisationseinheiten',
                'db_table': 'kiju_organisational_unit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hosts/', verbose_name='Logo')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ansprechpartner')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefonnummer')),
            ],
            options={
                'verbose_name': 'Einrichtung',
                'verbose_name_plural': 'Einrichtungen',
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Schlagwort',
                'verbose_name_plural': 'Schlagworte',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=100, verbose_name='Zielgruppe')),
            ],
            options={
                'verbose_name': 'Zielgruppe',
                'verbose_name_plural': 'Zielgruppen',
                'db_table': 'target_group',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='FamilyService',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Bild')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=25833, verbose_name='Geometrie')),
                ('street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Straße und Hausnummer')),
                ('zip', models.IntegerField(blank=True, null=True, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadt')),
                ('email', models.EmailField(max_length=255, verbose_name='E-Mail')),
                ('setting', models.TextField(verbose_name='Beratungssetting')),
                ('application_needed', models.BooleanField(verbose_name='Antrag erforderlich?')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefonnummer')),
                ('costs', models.FloatField(verbose_name='Kosten in Euro')),
                ('legal_basis', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.law', verbose_name='Gesetzliche Grundlage')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiju.provider', verbose_name='Anbieter')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.tag', verbose_name='Schlagworte')),
                ('target_group', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.targetgroup', verbose_name='Zielgruppe(n)')),
                ('topic', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.topic', verbose_name='Kategorie(n)')),
            ],
            options={
                'verbose_name': 'Angebot für Familien',
                'verbose_name_plural': 'Angebote für Familien',
            },
        ),
        migrations.CreateModel(
            name='ChildrenAndYouthService',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Bild')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=25833, verbose_name='Geometrie')),
                ('street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Straße und Hausnummer')),
                ('zip', models.IntegerField(blank=True, null=True, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadt')),
                ('email', models.EmailField(max_length=255, verbose_name='E-Mail')),
                ('setting', models.TextField(verbose_name='Beratungssetting')),
                ('application_needed', models.BooleanField(verbose_name='Antrag erforderlich?')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefonnummer')),
                ('costs', models.FloatField(verbose_name='Kosten in Euro')),
                ('legal_basis', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.law', verbose_name='Gesetzliche Grundlage')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiju.provider', verbose_name='Anbieter')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.tag', verbose_name='Schlagworte')),
                ('target_group', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.targetgroup', verbose_name='Zielgruppe(n)')),
                ('topic', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.topic', verbose_name='Kategorie(n)')),
            ],
            options={
                'verbose_name': 'Angebot für Kinder und Jugendliche',
                'verbose_name_plural': 'Angebote für Kinder und Jugendliche',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='ID des Django Users', unique=True, verbose_name='Benutzer-ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('organisational_unit', models.ForeignKey(blank=True, help_text='OE für Verwaltungsnutzer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='kiju.orgunit', verbose_name='Organisationseinheit')),
                ('provider', models.ForeignKey(blank=True, help_text='Träger für Einrichtungsnutzer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_users', to='kiju.provider', verbose_name='Träger')),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
                'db_table': 'kiju_user_profile',
            },
        ),
        migrations.CreateModel(
            name='WoftGService',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Bild')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=25833, verbose_name='Geometrie')),
                ('street', models.CharField(blank=True, max_length=150, null=True, verbose_name='Straße und Hausnummer')),
                ('zip', models.IntegerField(blank=True, null=True, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadt')),
                ('email', models.EmailField(max_length=255, verbose_name='E-Mail')),
                ('setting', models.TextField(verbose_name='Beratungssetting')),
                ('application_needed', models.BooleanField(verbose_name='Antrag erforderlich?')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefonnummer')),
                ('costs', models.FloatField(verbose_name='Kosten in Euro')),
                ('handicap_accessible', models.BooleanField(verbose_name='Barrierefreier Zugang?')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiju.provider', verbose_name='Anbieter')),
                ('legal_basis', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.law', verbose_name='Gesetzliche Grundlage')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.tag', verbose_name='Schlagworte')),
                ('target_group', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.targetgroup', verbose_name='Zielgruppe(n)')),
                ('topic', models.ManyToManyField(blank=True, related_name='%(class)s', to='kiju.topic', verbose_name='Kategorie(n)')),
            ],
            options={
                'verbose_name': 'Angebot im Rahmen des WoftG',
                'verbose_name_plural': 'Angebote im Rahmen des WoftG',
            },
        ),
        migrations.CreateModel(
            name='OrgUnitServicePermission',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('service_type', models.CharField(choices=kiju.models.base.get_service_type_choices, max_length=100, verbose_name='Angebotstyp')),
                ('organisational_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_permissions', to='kiju.orgunit', verbose_name='Organisationseinheit')),
            ],
            options={
                'verbose_name': 'OrgUnit-Service-Berechtigung',
                'verbose_name_plural': 'OrgUnit-Service-Berechtigungen',
                'db_table': 'kiju_org_unit_service_permission',
                'unique_together': {('organisational_unit', 'service_type')},
            },
        ),
    ]
