# Generated by Django 6.0.3 on 2026-03-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiju", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="childrenandyouthservice",
            name="catchment_area_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste von PyGeoAPI-Endpunkt-URIs. Für jeden Stadtteil im Einzugsgebiet wird die entsprechende Endpunkt-URI gespeichert.",
                verbose_name="Einzugsgebiet-URLs",
            ),
        ),
        migrations.AddField(
            model_name="childrenandyouthservice",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Datum, an dem das Angebot ausläuft.",
                null=True,
                verbose_name="Ablaufdatum",
            ),
        ),
        migrations.AddField(
            model_name="childrenandyouthservice",
            name="info_url",
            field=models.URLField(
                blank=True,
                help_text="Externe URL für weitere Informationen (z.B. Träger-Website).",
                max_length=500,
                null=True,
                verbose_name="Weiterführender Link",
            ),
        ),
        migrations.AddField(
            model_name="familyservice",
            name="catchment_area_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste von PyGeoAPI-Endpunkt-URIs. Für jeden Stadtteil im Einzugsgebiet wird die entsprechende Endpunkt-URI gespeichert.",
                verbose_name="Einzugsgebiet-URLs",
            ),
        ),
        migrations.AddField(
            model_name="familyservice",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Datum, an dem das Angebot ausläuft.",
                null=True,
                verbose_name="Ablaufdatum",
            ),
        ),
        migrations.AddField(
            model_name="familyservice",
            name="info_url",
            field=models.URLField(
                blank=True,
                help_text="Externe URL für weitere Informationen (z.B. Träger-Website).",
                max_length=500,
                null=True,
                verbose_name="Weiterführender Link",
            ),
        ),
        migrations.AddField(
            model_name="woftgservice",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Datum, an dem das Angebot ausläuft.",
                null=True,
                verbose_name="Ablaufdatum",
            ),
        ),
        migrations.AddField(
            model_name="woftgservice",
            name="info_url",
            field=models.URLField(
                blank=True,
                help_text="Externe URL für weitere Informationen (z.B. Träger-Website).",
                max_length=500,
                null=True,
                verbose_name="Weiterführender Link",
            ),
        ),
    ]
