# Generated by Django 5.2.3 on 2025-10-06 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('law_book', models.CharField(max_length=25, verbose_name='Gesetzesbuch (Abkürzung, z.B. SGB VIII)')),
                ('paragraph', models.CharField(max_length=25, verbose_name='Paragraoh (ohne §, z.B. 8a)')),
            ],
        ),
        migrations.RenameModel(
            old_name='Ferienangebot',
            new_name='HolidayService',
        ),
        migrations.CreateModel(
            name='PreventionService',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiju.service')),
                ('setting', models.TextField(verbose_name='Beratungssetting')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefonnummer')),
                ('costs', models.FloatField(verbose_name='Kosten in Euro')),
                ('application_needed', models.BooleanField(verbose_name='Antrag erforderlich?')),
                ('legal_basis', models.ManyToManyField(to='kiju.law', verbose_name='Gesetzliche Grundlage')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
            },
            bases=('kiju.service',),
        ),
        migrations.DeleteModel(
            name='Angebot',
        ),
    ]
