# Generated by Django 5.2.3 on 2025-10-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=100, verbose_name='Zielgruppe')),
            ],
            options={
                'verbose_name': 'Zielgruppe',
                'verbose_name_plural': 'Zielgruppen',
                'db_table': 'target_group',
            },
        ),
        migrations.AlterModelOptions(
            name='law',
            options={'verbose_name': 'Gesetz', 'verbose_name_plural': 'Gesetze'},
        ),
        migrations.AlterField(
            model_name='law',
            name='paragraph',
            field=models.CharField(max_length=25, verbose_name='Paragraph (ohne §, z.B. 8a)'),
        ),
        migrations.AlterField(
            model_name='preventionservice',
            name='legal_basis',
            field=models.ManyToManyField(blank=True, related_name='prevention_services', to='kiju.law', verbose_name='Gesetzliche Grundlage'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='topic',
        ),
        migrations.AlterModelTable(
            name='law',
            table='law',
        ),
        migrations.AddField(
            model_name='service',
            name='target_group',
            field=models.ManyToManyField(blank=True, related_name='services', to='kiju.targetgroup', verbose_name='Zielgruppe(n)'),
        ),
        migrations.AddField(
            model_name='service',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='services', to='kiju.topic', verbose_name='Kategorie(n)'),
        ),
    ]
