# Generated by Django 6.0.2 on 2026-03-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrenandyouthservice',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('in_review', 'In Prüfung'), ('revision_needed', 'Überarbeitung nötig'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='familyservice',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('in_review', 'In Prüfung'), ('revision_needed', 'Überarbeitung nötig'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='woftgservice',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('in_review', 'In Prüfung'), ('revision_needed', 'Überarbeitung nötig'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('service_type', models.CharField(max_length=100, verbose_name='Angebotstyp')),
                ('service_id', models.IntegerField(verbose_name='Service-ID')),
                ('created_by_user_id', models.IntegerField(verbose_name='Erstellt von (User-ID)')),
                ('task_status', models.CharField(choices=[('pending', 'Offen'), ('approved', 'Freigegeben'), ('rejected', 'Zurückgewiesen')], default='pending', max_length=20, verbose_name='Task-Status')),
                ('comments', models.JSONField(blank=True, default=dict, verbose_name='Feld-Kommentare')),
                ('approved_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Freigegebener Snapshot')),
                ('submitted_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Eingereichter Snapshot')),
                ('assigned_org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='kiju.orgunit', verbose_name='Zuständige OE')),
            ],
            options={
                'verbose_name': 'Prüfauftrag',
                'verbose_name_plural': 'Prüfaufträge',
                'db_table': 'kiju_review_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('message_type', models.CharField(choices=[('review_request', 'Prüfauftrag'), ('revision_request', 'Überarbeitungsauftrag')], max_length=30, verbose_name='Nachrichtentyp')),
                ('is_read', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('target_org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_messages', to='kiju.orgunit', verbose_name='Empfänger-OE')),
                ('target_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_messages', to='kiju.provider', verbose_name='Empfänger-Einrichtung')),
                ('review_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_messages', to='kiju.reviewtask', verbose_name='Prüfauftrag')),
            ],
            options={
                'verbose_name': 'Inbox-Nachricht',
                'verbose_name_plural': 'Inbox-Nachrichten',
                'db_table': 'kiju_inbox_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
