# Generated by Django 5.2.3 on 2025-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0002_alter_angebot_application_needed_alter_angebot_costs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angebot',
            name='costs',
            field=models.FloatField(blank=True, null=True, verbose_name='Kosten in Euro'),
        ),
        migrations.AlterField(
            model_name='angebot',
            name='legal_basis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gesetzliche Grundlage'),
        ),
        migrations.AlterField(
            model_name='angebot',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='angebot',
            name='setting',
            field=models.TextField(blank=True, null=True, verbose_name='Beratungssetting'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Bild'),
        ),
    ]
