# Generated by Django 6.0.2 on 2026-03-04 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0002_review_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrenandyouthservice',
            name='published_version',
            field=models.ForeignKey(blank=True, help_text='Zeigt auf den originalen published-Datensatz, von dem diese Draft-Copy abgeleitet wurde. Null bei normalen Services.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_copies', to='kiju.childrenandyouthservice', verbose_name='Veröffentlichte Version'),
        ),
        migrations.AddField(
            model_name='familyservice',
            name='published_version',
            field=models.ForeignKey(blank=True, help_text='Zeigt auf den originalen published-Datensatz, von dem diese Draft-Copy abgeleitet wurde. Null bei normalen Services.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_copies', to='kiju.familyservice', verbose_name='Veröffentlichte Version'),
        ),
        migrations.AddField(
            model_name='woftgservice',
            name='published_version',
            field=models.ForeignKey(blank=True, help_text='Zeigt auf den originalen published-Datensatz, von dem diese Draft-Copy abgeleitet wurde. Null bei normalen Services.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_copies', to='kiju.woftgservice', verbose_name='Veröffentlichte Version'),
        ),
    ]
