# Generated by Django 5.2.3 on 2025-10-13 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0002_targetgroup_alter_law_options_alter_law_paragraph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('email', models.EmailField(max_length=255, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefonnummer')),
            ],
            options={
                'verbose_name': 'Träger',
                'verbose_name_plural': 'Träger',
                'db_table': 'provider',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='kiju.provider', verbose_name='Träger'),
        ),
    ]
