# Generated by Django 6.0.3 on 2026-03-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiju", "0002_childrenandyouthservice_catchment_area_urls_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellung"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="letzte Änderung"),
                ),
                (
                    "service_type",
                    models.CharField(max_length=100, verbose_name="Angebotstyp"),
                ),
                ("service_id", models.IntegerField(verbose_name="Service-ID")),
                (
                    "image",
                    models.ImageField(upload_to="services/", verbose_name="Bild"),
                ),
                (
                    "position",
                    models.IntegerField(default=0, verbose_name="Reihenfolge"),
                ),
            ],
            options={
                "verbose_name": "Service-Bild",
                "verbose_name_plural": "Service-Bilder",
                "db_table": "kiju_service_image",
                "ordering": ["position", "pk"],
            },
        ),
        migrations.RemoveField(
            model_name="childrenandyouthservice",
            name="image",
        ),
        migrations.RemoveField(
            model_name="familyservice",
            name="image",
        ),
        migrations.RemoveField(
            model_name="woftgservice",
            name="image",
        ),
    ]
