# Generated by Django 6.0.3 on 2026-03-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiju", "0003_serviceimage_remove_childrenandyouthservice_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="angebotsdb/hosts/",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="image",
            field=models.ImageField(
                upload_to="angebotsdb/services/", verbose_name="Bild"
            ),
        ),
    ]
