# Generated by Django 5.2.3 on 2025-07-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0003_alter_angebot_costs_alter_angebot_legal_basis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferienangebot',
            name='costs',
            field=models.FloatField(blank=True, null=True, verbose_name='Teilnehmerbetrag in €'),
        ),
        migrations.AlterField(
            model_name='ferienangebot',
            name='maximum_participants',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='max. Teilnehmende'),
        ),
        migrations.AlterField(
            model_name='ferienangebot',
            name='meeting_point',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternativer Treffpunkt'),
        ),
        migrations.AlterField(
            model_name='ferienangebot',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeitpunkt'),
        ),
    ]
