# Generated by Django 5.2.3 on 2025-10-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0003_provider_host_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefonnummer'),
        ),
    ]
