# Generated by Django 5.2.3 on 2025-08-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0004_alter_ferienangebot_costs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='topic',
        ),
        migrations.AddField(
            model_name='service',
            name='topics',
            field=models.ManyToManyField(blank=True, to='kiju.topic', verbose_name='Kategorien'),
        ),
    ]
