# Generated by Django 6.0.3 on 2026-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiju", "0004_alter_provider_logo_alter_serviceimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="childrenandyouthservice",
            name="contact_hours",
            field=models.TextField(
                blank=True,
                help_text="z.B. Mo Di Mi 7:30 - 15:00 Uhr, Do 8:00 - 13:00 Uhr",
                null=True,
                verbose_name="Kontaktzeiträume",
            ),
        ),
        migrations.AddField(
            model_name="familyservice",
            name="contact_hours",
            field=models.TextField(
                blank=True,
                help_text="z.B. Mo Di Mi 7:30 - 15:00 Uhr, Do 8:00 - 13:00 Uhr",
                null=True,
                verbose_name="Kontaktzeiträume",
            ),
        ),
        migrations.AddField(
            model_name="woftgservice",
            name="contact_hours",
            field=models.TextField(
                blank=True,
                help_text="z.B. Mo Di Mi 7:30 - 15:00 Uhr, Do 8:00 - 13:00 Uhr",
                null=True,
                verbose_name="Kontaktzeiträume",
            ),
        ),
        migrations.AlterField(
            model_name="childrenandyouthservice",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Gemeinde"
            ),
        ),
        migrations.AlterField(
            model_name="familyservice",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Gemeinde"
            ),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Gemeinde"
            ),
        ),
    ]
