# Generated by Django 5.2.3 on 2025-10-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0004_alter_provider_address_alter_provider_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventionservice',
            options={'verbose_name': 'Präventionsangebot', 'verbose_name_plural': 'Präventionsangebote'},
        ),
        migrations.AddField(
            model_name='provider',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='provider',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Straße und Hausnummer'),
        ),
        migrations.AddField(
            model_name='provider',
            name='zip',
            field=models.IntegerField(blank=True, null=True, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='host',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hosts/', verbose_name='Logo'),
        ),
    ]
