# Generated by Django 6.0.3 on 2026-03-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiju", "0005_childrenandyouthservice_contact_hours_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="law",
            options={
                "ordering": ["law_book", "paragraph"],
                "verbose_name": "Gesetz",
                "verbose_name_plural": "Gesetze",
            },
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={
                "ordering": ["name"],
                "verbose_name": "Träger",
                "verbose_name_plural": "Träger",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Schlagwort",
                "verbose_name_plural": "Schlagworte",
            },
        ),
        migrations.AlterModelOptions(
            name="targetgroup",
            options={
                "ordering": ["name"],
                "verbose_name": "Zielgruppe",
                "verbose_name_plural": "Zielgruppen",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["name"],
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
            },
        ),
        migrations.AlterField(
            model_name="childrenandyouthservice",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Gemeinde"),
        ),
        migrations.AlterField(
            model_name="childrenandyouthservice",
            name="expiry_date",
            field=models.DateField(
                help_text="Datum, an dem das Angebot ausläuft.",
                verbose_name="Ablaufdatum",
            ),
        ),
        migrations.AlterField(
            model_name="childrenandyouthservice",
            name="legal_basis",
            field=models.ManyToManyField(
                related_name="%(class)s",
                to="kiju.law",
                verbose_name="Gesetzliche Grundlage",
            ),
        ),
        migrations.AlterField(
            model_name="childrenandyouthservice",
            name="setting",
            field=models.TextField(
                blank=True, null=True, verbose_name="Beratungssetting"
            ),
        ),
        migrations.AlterField(
            model_name="childrenandyouthservice",
            name="street",
            field=models.CharField(
                max_length=150, verbose_name="Straße und Hausnummer"
            ),
        ),
        migrations.AlterField(
            model_name="childrenandyouthservice",
            name="topic",
            field=models.ManyToManyField(
                related_name="%(class)s", to="kiju.topic", verbose_name="Kategorie(n)"
            ),
        ),
        migrations.AlterField(
            model_name="childrenandyouthservice",
            name="zip",
            field=models.IntegerField(verbose_name="PLZ"),
        ),
        migrations.AlterField(
            model_name="familyservice",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Gemeinde"),
        ),
        migrations.AlterField(
            model_name="familyservice",
            name="expiry_date",
            field=models.DateField(
                help_text="Datum, an dem das Angebot ausläuft.",
                verbose_name="Ablaufdatum",
            ),
        ),
        migrations.AlterField(
            model_name="familyservice",
            name="legal_basis",
            field=models.ManyToManyField(
                related_name="%(class)s",
                to="kiju.law",
                verbose_name="Gesetzliche Grundlage",
            ),
        ),
        migrations.AlterField(
            model_name="familyservice",
            name="street",
            field=models.CharField(
                max_length=150, verbose_name="Straße und Hausnummer"
            ),
        ),
        migrations.AlterField(
            model_name="familyservice",
            name="topic",
            field=models.ManyToManyField(
                related_name="%(class)s", to="kiju.topic", verbose_name="Kategorie(n)"
            ),
        ),
        migrations.AlterField(
            model_name="familyservice",
            name="zip",
            field=models.IntegerField(verbose_name="PLZ"),
        ),
        migrations.AlterField(
            model_name="targetgroup",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Zielgruppe"
            ),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Gemeinde"),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="expiry_date",
            field=models.DateField(
                help_text="Datum, an dem das Angebot ausläuft.",
                verbose_name="Ablaufdatum",
            ),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="legal_basis",
            field=models.ManyToManyField(
                related_name="%(class)s",
                to="kiju.law",
                verbose_name="Gesetzliche Grundlage",
            ),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="street",
            field=models.CharField(
                max_length=150, verbose_name="Straße und Hausnummer"
            ),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="topic",
            field=models.ManyToManyField(
                related_name="%(class)s", to="kiju.topic", verbose_name="Kategorie(n)"
            ),
        ),
        migrations.AlterField(
            model_name="woftgservice",
            name="zip",
            field=models.IntegerField(verbose_name="PLZ"),
        ),
    ]
