# Generated by Django 5.2.3 on 2025-10-24 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0005_alter_preventionservice_options_provider_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'Einrichtung', 'verbose_name_plural': 'Einrichtungen'},
        ),
        migrations.AlterField(
            model_name='host',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='host',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ansprechpartner'),
        ),
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='host',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='host',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='service',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiju.host', verbose_name='Anbieter'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Bild'),
        ),
    ]
