# Generated by Django 6.0.3 on 2026-03-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiju", "0006_alter_law_options_alter_provider_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewtask",
            name="reviewed_by_user_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Geprüft von (User-ID)"
            ),
        ),
        migrations.AlterField(
            model_name="childrenandyouthservice",
            name="catchment_area_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste von PyGeoAPI-Endpunkt-URIs. Für jeden Stadtteil im Einzugsgebiet wird die entsprechende Endpunkt-URI gespeichert.",
                verbose_name="Einzugsgebiet",
            ),
        ),
        migrations.AlterField(
            model_name="familyservice",
            name="catchment_area_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste von PyGeoAPI-Endpunkt-URIs. Für jeden Stadtteil im Einzugsgebiet wird die entsprechende Endpunkt-URI gespeichert.",
                verbose_name="Einzugsgebiet",
            ),
        ),
    ]
