# Generated by Django 5.2.3 on 2025-10-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0006_alter_host_options_alter_host_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Themenfeld', 'verbose_name_plural': 'Themenfelder'},
        ),
    ]
