# Generated by Django 5.2.3 on 2025-11-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0007_alter_topic_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='geometrie',
            new_name='geometry',
        ),
    ]
