# Generated by Django 5.2.3 on 2025-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0008_rename_geometrie_service_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Schlagwort',
                'verbose_name_plural': 'Schlagworte',
                'db_table': 'tag',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='services', to='kiju.tag', verbose_name='Schlagworte'),
        ),
    ]
