# Generated by Django 5.2.3 on 2025-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiju', '0009_tag_service_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='address',
        ),
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='service',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Straße und Hausnummer'),
        ),
        migrations.AddField(
            model_name='service',
            name='zip',
            field=models.IntegerField(blank=True, null=True, verbose_name='PLZ'),
        ),
        migrations.DeleteModel(
            name='HolidayService',
        ),
    ]
