@startuml
skinparam linetype ortho

package accounts {
  class login {
    {field} title
    {field} content
  }

  class login_add_token {
    {field} title
    {field} content
  }

  class logout {
    {field} title
    {field} content
  }

  class test {
    {field} content
  }
}


datenwerft.base <|-- accounts.login
datenwerft.base <|-- accounts.login_add_token
datenwerft.base <|-- accounts.logout
datenwerft.base <|-- accounts.test

@enduml