@startuml
package datenwerft{
  class base {
    {field} head
    {field} meta
    {field} title
    {field} style
    {field} scripts
    {field} navbar
    {field} content
    {field} footer
    {method} include navbar_html
  }

  class navbar_html {
    {field} navbar
  }

  class index {
    {field} title
    {field} content
  }

  class error {
    {field} title
    {field} content
  }

  class modal_confirm_export {}
  class modal_error {}
  class modal_loading {}
}

package accounts {
  class login {
    {field} title
    {field} content
  }

  class login_add_token {
    {field} title
    {field} content
  }

  class logout {
    {field} title
    {field} content
  }

  class test {
    {field} content
  }
}


datenwerft.base ..> datenwerft.navbar_html
datenwerft.base <|-- datenwerft.index
datenwerft.base <|-- datenwerft.error

datenwerft.base <|-- accounts.login
datenwerft.base <|-- accounts.login_add_token
datenwerft.base <|-- accounts.logout
datenwerft.base <|-- accounts.test

@enduml