# Generated by Django 5.0.6 on 2024-06-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail-Adresse'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail-Adresse'),
        ),
    ]
