# Generated by Django 5.0.6 on 2024-06-21 10:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanupeventcontainer',
            name='place',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Containerstandort'),
        ),
        migrations.AlterField(
            model_name='cleanupeventevent',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Fläche für Müllsammelaktion'),
        ),
        migrations.AlterField(
            model_name='cleanupeventvenue',
            name='place',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Treffpunkt für Müllsammelaktion'),
        ),
    ]
