# Generated by Django 5.1.4 on 2025-01-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanupeventdetails',
            name='equipments',
            field=models.ManyToManyField(blank=True, db_table='cleanupevent_details_equipments', to='antragsmanagement.cleanupeventcodelistequipment', verbose_name=' benötigte Ausstattung(en)'),
        ),
        migrations.CreateModel(
            name='CleanupEventRequestComment',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellung')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='letzte Änderung')),
                ('user_id', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='User-ID')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('send_to_requester', models.BooleanField(default=False, verbose_name='Kommentar auch per E-Mail an Antragsteller:in senden?')),
                ('cleanupevent_request', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='antragsmanagement.cleanupeventrequest', verbose_name='Antrag')),
            ],
            options={
                'verbose_name': 'Müllsammelaktion: Kommentar zu Antrag',
                'verbose_name_plural': 'Müllsammelaktionen: Kommentare zu Anträgen',
                'db_table': 'cleanupevent_request_comment',
                'ordering': ['-cleanupevent_request', '-created'],
                'get_latest_by': 'modified',
                'abstract': False,
                'indexes': [models.Index(fields=['cleanupevent_request'], name='cleanupeven_cleanup_d18462_idx')],
            },
        ),
    ]
