# Generated by Django 5.1.4 on 2025-01-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0003_alter_cleanupeventdetails_equipments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CleanupEventComment',
            new_name='CleanupEventRequestComment',
        ),
    ]
