# Generated by Django 6.1 on 2026-08-20 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0003_alter_cleanupeventdetails_equipments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='telephone',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Die Schreibweise einer Telefonnummer muss der Empfehlung E.123 der Internationalen Fernmeldeunion entsprechen und daher folgendes Format aufweisen (Beispiel): +49 381 3816256', regex='^\\+(1 )?([0-9]{1,3}) [1-9][0-9]{1,5} [0-9]{1,13}$')], verbose_name='Telefonnummer'),
        ),
    ]
