# Generated by Django 5.0.6 on 2024-06-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0003_alter_authority_email_alter_requester_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(verbose_name='Inhalt'),
        ),
    ]
