# Generated by Django 5.0.7 on 2024-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0004_alter_cleanupeventresponsibilities_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cleanupeventresponsibilities',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cleanupeventresponsibilities',
            constraint=models.UniqueConstraint(fields=('cleanupevent_request', 'authority'), name='unique_cleanupevent_request_authority'),
        ),
        migrations.AddConstraint(
            model_name='cleanupeventresponsibilities',
            constraint=models.UniqueConstraint(condition=models.Q(('main', True)), fields=('cleanupevent_request',), name='unique_cleanupevent_request_main_when_main_true'),
        ),
    ]
