# Generated by Django 5.0.6 on 2024-06-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0004_alter_email_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requester',
            name='registered',
        ),
        migrations.AddField(
            model_name='requester',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='User-ID'),
        ),
    ]
