# Generated by Django 5.0.6 on 2024-06-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0005_remove_requester_registered_requester_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanupeventrequest',
            name='responsibilities',
            field=models.ManyToManyField(blank=True, db_table='cleanupevent_responsibilities', editable=False, to='antragsmanagement.authority', verbose_name='Zuständigkeit(en)'),
        ),
    ]
