# Generated by Django 5.0.6 on 2024-07-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0005_cleanupeventrequest_comment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cleanupeventcontainer',
            index=models.Index(fields=['cleanupevent_request'], name='cleanupeven_cleanup_95952b_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanupeventdetails',
            index=models.Index(fields=['cleanupevent_request'], name='cleanupeven_cleanup_88f00b_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanupeventevent',
            index=models.Index(fields=['cleanupevent_request'], name='cleanupeven_cleanup_3a0312_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanupeventrequest',
            index=models.Index(fields=['status'], name='cleanupeven_status__42ab78_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanupeventrequest',
            index=models.Index(fields=['requester'], name='cleanupeven_request_f0fae3_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanupeventvenue',
            index=models.Index(fields=['cleanupevent_request'], name='cleanupeven_cleanup_4245a3_idx'),
        ),
    ]
