# Generated by Django 5.0.6 on 2024-06-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0006_alter_cleanupeventrequest_responsibilities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleanupeventcodelistequipment',
            options={'get_latest_by': 'modified', 'ordering': ['ordinal', 'name'], 'verbose_name': 'Müllsammelaktion: Austattung', 'verbose_name_plural': 'Müllsammelaktionen: Austattungen'},
        ),
        migrations.AlterModelOptions(
            name='cleanupeventcodelistwastequantity',
            options={'get_latest_by': 'modified', 'ordering': ['ordinal', 'name'], 'verbose_name': 'Müllsammelaktion: Abfallmenge', 'verbose_name_plural': 'Müllsammelaktionen: Abfallmengen'},
        ),
        migrations.AlterModelOptions(
            name='cleanupeventcodelistwastetype',
            options={'get_latest_by': 'modified', 'ordering': ['ordinal', 'name'], 'verbose_name': 'Müllsammelaktion: Abfallart', 'verbose_name_plural': 'Müllsammelaktionen: Abfallarten'},
        ),
        migrations.AlterModelOptions(
            name='cleanupeventcontainer',
            options={'get_latest_by': 'modified', 'ordering': ['-cleanupevent_request'], 'verbose_name': 'Müllsammelaktion: Container zu Antrag', 'verbose_name_plural': 'Müllsammelaktionen: Container zu Anträgen'},
        ),
        migrations.AlterModelOptions(
            name='cleanupeventdetails',
            options={'get_latest_by': 'modified', 'ordering': ['-cleanupevent_request'], 'verbose_name': 'Müllsammelaktion: Detailangaben zu Antrag', 'verbose_name_plural': 'Müllsammelaktionen: Detailangaben zu Anträgen'},
        ),
        migrations.AlterModelOptions(
            name='cleanupeventevent',
            options={'get_latest_by': 'modified', 'ordering': ['-cleanupevent_request'], 'verbose_name': 'Müllsammelaktion: Aktionen zu Antrag', 'verbose_name_plural': 'Müllsammelaktionen: Aktionen zu Anträgen'},
        ),
        migrations.AlterModelOptions(
            name='cleanupeventrequest',
            options={'get_latest_by': 'modified', 'ordering': ['-id'], 'verbose_name': 'Müllsammelaktion: Antrag', 'verbose_name_plural': 'Müllsammelaktionen: Anträge'},
        ),
        migrations.AlterModelOptions(
            name='cleanupeventvenue',
            options={'get_latest_by': 'modified', 'ordering': ['-cleanupevent_request'], 'verbose_name': 'Müllsammelaktion: Treffpunkt zu Antrag', 'verbose_name_plural': 'Müllsammelaktionen: Treffpunkte zu Anträgen'},
        ),
    ]
