# Generated by Django 5.0.6 on 2024-06-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0007_alter_cleanupeventcodelistequipment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleanupeventcontainer',
            options={'get_latest_by': 'modified', 'ordering': ['-cleanupevent_request'], 'verbose_name': 'Müllsammelaktion: Container', 'verbose_name_plural': 'Müllsammelaktionen: Container'},
        ),
        migrations.AlterModelOptions(
            name='cleanupeventdetails',
            options={'get_latest_by': 'modified', 'ordering': ['-cleanupevent_request'], 'verbose_name': 'Müllsammelaktion: Detailangaben', 'verbose_name_plural': 'Müllsammelaktionen: Detailangaben'},
        ),
        migrations.AlterModelOptions(
            name='cleanupeventevent',
            options={'get_latest_by': 'modified', 'ordering': ['-cleanupevent_request'], 'verbose_name': 'Müllsammelaktion: Aktionsdaten', 'verbose_name_plural': 'Müllsammelaktionen: Aktionsdaten'},
        ),
        migrations.AlterModelOptions(
            name='cleanupeventvenue',
            options={'get_latest_by': 'modified', 'ordering': ['-cleanupevent_request'], 'verbose_name': 'Müllsammelaktion: Treffpunkt', 'verbose_name_plural': 'Müllsammelaktionen: Treffpunkte'},
        ),
        migrations.AlterField(
            model_name='cleanupeventevent',
            name='from_date',
            field=models.DateField(verbose_name='Startdatum/Datum'),
        ),
        migrations.AlterField(
            model_name='cleanupeventevent',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Enddatum'),
        ),
    ]
