# Generated by Django 5.0.6 on 2024-06-18 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0008_alter_cleanupeventcontainer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanupeventcontainer',
            name='cleanupevent_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antragsmanagement.cleanupeventrequest', unique=True, verbose_name='Antrag'),
        ),
        migrations.AlterField(
            model_name='cleanupeventdetails',
            name='cleanupevent_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antragsmanagement.cleanupeventrequest', unique=True, verbose_name='Antrag'),
        ),
        migrations.AlterField(
            model_name='cleanupeventevent',
            name='cleanupevent_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antragsmanagement.cleanupeventrequest', unique=True, verbose_name='Antrag'),
        ),
        migrations.AlterField(
            model_name='cleanupeventvenue',
            name='cleanupevent_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antragsmanagement.cleanupeventrequest', unique=True, verbose_name='Antrag'),
        ),
    ]
