# Generated by Django 5.0.6 on 2024-06-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0009_alter_cleanupeventcontainer_cleanupevent_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanupeventcontainer',
            name='cleanupevent_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='antragsmanagement.cleanupeventrequest', verbose_name='Antrag'),
        ),
        migrations.AlterField(
            model_name='cleanupeventdetails',
            name='cleanupevent_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='antragsmanagement.cleanupeventrequest', verbose_name='Antrag'),
        ),
        migrations.AlterField(
            model_name='cleanupeventevent',
            name='cleanupevent_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='antragsmanagement.cleanupeventrequest', verbose_name='Antrag'),
        ),
        migrations.AlterField(
            model_name='cleanupeventvenue',
            name='cleanupevent_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='antragsmanagement.cleanupeventrequest', verbose_name='Antrag'),
        ),
    ]
