# Generated by Django 5.0.6 on 2024-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antragsmanagement', '0010_alter_cleanupeventcontainer_cleanupevent_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanupeventcontainer',
            name='delivery_date',
            field=models.DateField(verbose_name='Stellungsdatum'),
        ),
        migrations.AlterField(
            model_name='cleanupeventcontainer',
            name='pickup_date',
            field=models.DateField(verbose_name='Abholdatum'),
        ),
    ]
