# Generated by Django 5.2 on 2025-05-07 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdihrometadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Es dürfen nur Kleinbuchstaben – exklusive ä, ö, ü sowie ß – und Bindestriche verwendet werden.', regex='^[a-z-]*$')], verbose_name='Name'),
        ),
    ]
