# Generated by Django 4.1.7 on 2023-03-07 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
  ]

  operations = [
    migrations.CreateModel(
      name='Sector',
      fields=[
        ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('title', models.CharField(max_length=255, unique=True, validators=[
          django.core.validators.RegexValidator(
            message='Texte dürfen keine Akute (´) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*´).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Schreibmaschinensatz-Anführungszeichen (") enthalten. Stattdessen müssen die typographisch korrekten Anführungszeichen („“) verwendet werden.',
            regex='^(?!.*\\").*$'), django.core.validators.RegexValidator(
            message="Texte dürfen keine einfachen Schreibmaschinensatz-Anführungszeichen (') enthalten. Stattdessen muss der typographisch korrekte Apostroph(’) verwendet werden.",
            regex="^(?!.*\\').*$"), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Leerzeichen und/oder Zeilenumbrüche enthalten.',
            regex='^(?!.*  ).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine Gravis (`) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*`).*$')], verbose_name='Titel')),
      ],
      options={
        'verbose_name': 'Branche',
        'verbose_name_plural': 'Branchen',
        'db_table': 'codelist_sector',
        'ordering': ['title'],
        'get_latest_by': 'updated_at',
        'abstract': False,
      },
    ),
    migrations.CreateModel(
      name='Status',
      fields=[
        ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('ordinal', models.SmallIntegerField(unique=True, verbose_name='Ordinalzahl')),
        ('title', models.CharField(max_length=255, unique=True, validators=[
          django.core.validators.RegexValidator(
            message='Texte dürfen keine Akute (´) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*´).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Schreibmaschinensatz-Anführungszeichen (") enthalten. Stattdessen müssen die typographisch korrekten Anführungszeichen („“) verwendet werden.',
            regex='^(?!.*\\").*$'), django.core.validators.RegexValidator(
            message="Texte dürfen keine einfachen Schreibmaschinensatz-Anführungszeichen (') enthalten. Stattdessen muss der typographisch korrekte Apostroph(’) verwendet werden.",
            regex="^(?!.*\\').*$"), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Leerzeichen und/oder Zeilenumbrüche enthalten.',
            regex='^(?!.*  ).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine Gravis (`) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*`).*$')], verbose_name='Titel')),
        ('icon', models.CharField(max_length=255, unique=True, validators=[
          django.core.validators.RegexValidator(
            message='Texte dürfen keine Akute (´) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*´).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Schreibmaschinensatz-Anführungszeichen (") enthalten. Stattdessen müssen die typographisch korrekten Anführungszeichen („“) verwendet werden.',
            regex='^(?!.*\\").*$'), django.core.validators.RegexValidator(
            message="Texte dürfen keine einfachen Schreibmaschinensatz-Anführungszeichen (') enthalten. Stattdessen muss der typographisch korrekte Apostroph(’) verwendet werden.",
            regex="^(?!.*\\').*$"), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Leerzeichen und/oder Zeilenumbrüche enthalten.',
            regex='^(?!.*  ).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine Gravis (`) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*`).*$')], verbose_name='Icon')),
      ],
      options={
        'verbose_name': 'Bearbeitungsstatus',
        'verbose_name_plural': 'Bearbeitungsstatus',
        'db_table': 'codelist_status',
        'ordering': ['ordinal'],
        'get_latest_by': 'updated_at',
        'abstract': False,
      },
    ),
    migrations.CreateModel(
      name='TypeOfEvent',
      fields=[
        ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('title', models.CharField(max_length=255, unique=True, validators=[
          django.core.validators.RegexValidator(
            message='Texte dürfen keine Akute (´) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*´).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Schreibmaschinensatz-Anführungszeichen (") enthalten. Stattdessen müssen die typographisch korrekten Anführungszeichen („“) verwendet werden.',
            regex='^(?!.*\\").*$'), django.core.validators.RegexValidator(
            message="Texte dürfen keine einfachen Schreibmaschinensatz-Anführungszeichen (') enthalten. Stattdessen muss der typographisch korrekte Apostroph(’) verwendet werden.",
            regex="^(?!.*\\').*$"), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Leerzeichen und/oder Zeilenumbrüche enthalten.',
            regex='^(?!.*  ).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine Gravis (`) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*`).*$')], verbose_name='Titel')),
        ('icon', models.CharField(max_length=255, unique=True, validators=[
          django.core.validators.RegexValidator(
            message='Texte dürfen keine Akute (´) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*´).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Schreibmaschinensatz-Anführungszeichen (") enthalten. Stattdessen müssen die typographisch korrekten Anführungszeichen („“) verwendet werden.',
            regex='^(?!.*\\").*$'), django.core.validators.RegexValidator(
            message="Texte dürfen keine einfachen Schreibmaschinensatz-Anführungszeichen (') enthalten. Stattdessen muss der typographisch korrekte Apostroph(’) verwendet werden.",
            regex="^(?!.*\\').*$"), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Leerzeichen und/oder Zeilenumbrüche enthalten.',
            regex='^(?!.*  ).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine Gravis (`) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*`).*$')], verbose_name='Icon')),
      ],
      options={
        'verbose_name': 'Ereignisart',
        'verbose_name_plural': 'Ereignisarten',
        'db_table': 'codelist_typeofevent',
        'ordering': ['title'],
        'get_latest_by': 'updated_at',
        'abstract': False,
      },
    ),
    migrations.CreateModel(
      name='TypeOfImmission',
      fields=[
        ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('title', models.CharField(max_length=255, unique=True, validators=[
          django.core.validators.RegexValidator(
            message='Texte dürfen keine Akute (´) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*´).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Schreibmaschinensatz-Anführungszeichen (") enthalten. Stattdessen müssen die typographisch korrekten Anführungszeichen („“) verwendet werden.',
            regex='^(?!.*\\").*$'), django.core.validators.RegexValidator(
            message="Texte dürfen keine einfachen Schreibmaschinensatz-Anführungszeichen (') enthalten. Stattdessen muss der typographisch korrekte Apostroph(’) verwendet werden.",
            regex="^(?!.*\\').*$"), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Leerzeichen und/oder Zeilenumbrüche enthalten.',
            regex='^(?!.*  ).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine Gravis (`) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*`).*$')], verbose_name='Titel')),
        ('icon', models.CharField(max_length=255, unique=True, validators=[
          django.core.validators.RegexValidator(
            message='Texte dürfen keine Akute (´) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*´).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Schreibmaschinensatz-Anführungszeichen (") enthalten. Stattdessen müssen die typographisch korrekten Anführungszeichen („“) verwendet werden.',
            regex='^(?!.*\\").*$'), django.core.validators.RegexValidator(
            message="Texte dürfen keine einfachen Schreibmaschinensatz-Anführungszeichen (') enthalten. Stattdessen muss der typographisch korrekte Apostroph(’) verwendet werden.",
            regex="^(?!.*\\').*$"), django.core.validators.RegexValidator(
            message='Texte dürfen keine doppelten Leerzeichen und/oder Zeilenumbrüche enthalten.',
            regex='^(?!.*  ).*$'), django.core.validators.RegexValidator(
            message='Texte dürfen keine Gravis (`) enthalten. Stattdessen muss der typographisch korrekte Apostroph (’) verwendet werden.',
            regex='^(?!.*`).*$')], verbose_name='Icon')),
      ],
      options={
        'verbose_name': 'Immissionsart',
        'verbose_name_plural': 'Immissionsarten',
        'db_table': 'codelist_typeofimmission',
        'ordering': ['title'],
        'get_latest_by': 'updated_at',
        'abstract': False,
      },
    ),
    migrations.AddConstraint(
      model_name='status',
      constraint=models.CheckConstraint(check=models.Q(('ordinal__gte', 1)),
                                        name='status_ordinal_gte_1'),
    ),
  ]
