# Generated by Django 4.2.1 on 2023-05-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0002_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'get_latest_by': 'updated_at', 'ordering': ['-created_at'], 'verbose_name': 'Eintrag im Bearbeitungsverlauf', 'verbose_name_plural': 'Einträge im Bearbeitungsverlauf'},
        ),
    ]
