# Generated by Django 4.2 on 2023-04-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0002_auto_20230412_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bemas.status', verbose_name='Bearbeitungsstatus'),
        ),
    ]
