# Generated by Django 4.2 on 2023-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0002_auto_20230420_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complainers_organizations',
            field=models.ManyToManyField(blank=True, db_table='complainers_organizations', to='bemas.organization', verbose_name='Beschwerdeführerin'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainers_persons',
            field=models.ManyToManyField(blank=True, db_table='complainers_persons', to='bemas.person', verbose_name='Beschwerdeführer:in'),
        ),
    ]
