# Generated by Django 4.1.7 on 2023-03-28 13:32

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telephone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die Schreibweise von <strong><em>Rufnummern</em></strong> muss der Empfehlung E.123 der Internationalen Fernmeldeunion entsprechen und daher folgendes Format aufweisen (Beispiel): +49 381 3816256', regex='^\\+(1 )?([0-9]{1,3}) [1-9][0-9]{1,5} [0-9]{1,13}$')], verbose_name='Telefonnummer(n)'), blank=True, null=True, size=None, verbose_name='Telefonnummer(n)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator(message='Die <strong><em>E-Mail-Adresse</em></strong> muss syntaktisch korrekt sein und daher folgendes Format aufweisen (Beispiel): abc-123.098_zyx@xyz-567.def.abc')], verbose_name='E-Mail-Adresse(n)'), blank=True, null=True, size=None, verbose_name='E-Mail-Adresse(n)'),
        ),
    ]
