# Generated by Django 4.2 on 2023-04-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0003_alter_complaint_complainers_organizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complainers_organizations',
            field=models.ManyToManyField(blank=True, db_table='complainers_organizations', to='bemas.organization', verbose_name='Organisation(en) als Beschwerdeführerin(nen)'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainers_persons',
            field=models.ManyToManyField(blank=True, db_table='complainers_persons', to='bemas.person', verbose_name='Person(en) als Beschwerdeführer:in(nen)'),
        ),
    ]
