# Generated by Django 4.2.6 on 2023-10-27 12:20

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0003_alter_complaint_dms_link_alter_event_dms_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='telephone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die Schreibweise von Telefonnummern muss der Empfehlung E.123 der Internationalen Fernmeldeunion entsprechen und daher folgendes Format aufweisen (Beispiel): +49 381 3816256', regex='^\\+(1 )?([0-9]{1,3}) [1-9][0-9]{1,5} [0-9]{1,13}$')], verbose_name='Telefonnummer(n)'), blank=True, null=True, size=None, verbose_name='Telefonnummer(n)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die Schreibweise von Telefonnummern muss der Empfehlung E.123 der Internationalen Fernmeldeunion entsprechen und daher folgendes Format aufweisen (Beispiel): +49 381 3816256', regex='^\\+(1 )?([0-9]{1,3}) [1-9][0-9]{1,5} [0-9]{1,13}$')], verbose_name='Telefonnummer(n)'), blank=True, null=True, size=None, verbose_name='Telefonnummer(n)'),
        ),
    ]
