# Generated by Django 4.2 on 2023-04-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0004_alter_complaint_complainers_organizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='search_content',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='search_content',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='search_content',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='originator',
            name='search_content',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='search_content',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
