# Generated by Django 5.0.2 on 2024-02-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0004_alter_organization_telephone_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, choices=[('Frau', 'Frau'), ('Herr', 'Herr')], max_length=255, null=True, verbose_name='Anrede'),
        ),
    ]
