# Generated by Django 5.0.2 on 2024-02-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0005_event_point_in_time_person_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'updated_at', 'ordering': ['-complaint__id', '-date'], 'verbose_name': 'Journalereignis', 'verbose_name_plural': 'Journalereignisse'},
        ),
    ]
