# Generated by Django 4.2 on 2023-04-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0005_contact_search_content_event_search_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='search_content',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
