# Generated by Django 4.1.7 on 2023-03-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0005_address_alter_person_email_addresses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bemas.address', verbose_name='Anschrift'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(check=models.Q(('house_number__gte', 1)), name='address_house_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(check=models.Q(('house_number__lte', 999)), name='address_house_number_lte_999'),
        ),
    ]
