# Generated by Django 5.0.3 on 2024-03-26 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0006_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='dms_link',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Der <strong><em>d.3</em></strong>-Vorgang muss folgendes Format aufweisen (Beispiele): 512.431-003/002 oder 002.13 oder 114.521-025', regex='^[0-9]{3}\\.[0-9]{1,5}(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dms_link',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Der <strong><em>d.3</em></strong>-Vorgang muss folgendes Format aufweisen (Beispiele): 512.431-003/002 oder 002.13 oder 114.521-025', regex='^[0-9]{3}\\.[0-9]{1,5}(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='dms_link',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Der <strong><em>d.3</em></strong>-Vorgang muss folgendes Format aufweisen (Beispiele): 512.431-003/002 oder 002.13 oder 114.521-025', regex='^[0-9]{3}\\.[0-9]{1,5}(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3'),
        ),
        migrations.AlterField(
            model_name='originator',
            name='dms_link',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Der <strong><em>d.3</em></strong>-Vorgang muss folgendes Format aufweisen (Beispiele): 512.431-003/002 oder 002.13 oder 114.521-025', regex='^[0-9]{3}\\.[0-9]{1,5}(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3'),
        ),
    ]
