# Generated by Django 4.1.7 on 2023-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0006_person_address_address_address_house_number_gte_1_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('place', 'postal_code', 'street', 'house_number', 'house_number_suffix'), name='address_unique'),
        ),
    ]
