# Generated by Django 4.2 on 2023-04-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0006_complaint_search_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='object_str',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Objekt'),
        ),
    ]
