# Generated by Django 4.1.7 on 2023-03-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0007_address_address_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='address_unique',
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('place', 'postal_code', 'street', 'house_number', 'house_number_suffix'), name='address_with_house_number_suffix_unique'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('house_number_suffix__isnull', True)), fields=('place', 'postal_code', 'street', 'house_number'), name='address_without_house_number_suffix_unique'),
        ),
    ]
