# Generated by Django 5.0.6 on 2024-05-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0008_alter_event_options_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='academic_title',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Prof.', 'Prof.')], max_length=255, null=True, verbose_name='akademischer Titel'),
        ),
    ]
