# Generated by Django 5.2.9 on 2025-12-04 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0010_alter_person_academic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='dms_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die <strong><em>d.3</em></strong>-Nummer muss folgendes Format aufweisen (Beispiele): 002.13 (für eine Betreffeinheit) oder 522.13.018 (für eine Betreffeinheit) oder 114.521-025 (für eine Akte) oder 554.311.01-008 (für eine Akte) oder 512.431-003/002 (für einen Vorgang) oder 554.311.01-008/002 (für einen Vorgang).', regex='^[0-9]{3}\\.[0-9]{1,5}(\\.[0-9]{1,5})?(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dms_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die <strong><em>d.3</em></strong>-Nummer muss folgendes Format aufweisen (Beispiele): 002.13 (für eine Betreffeinheit) oder 522.13.018 (für eine Betreffeinheit) oder 114.521-025 (für eine Akte) oder 554.311.01-008 (für eine Akte) oder 512.431-003/002 (für einen Vorgang) oder 554.311.01-008/002 (für einen Vorgang).', regex='^[0-9]{3}\\.[0-9]{1,5}(\\.[0-9]{1,5})?(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='dms_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die <strong><em>d.3</em></strong>-Nummer muss folgendes Format aufweisen (Beispiele): 002.13 (für eine Betreffeinheit) oder 522.13.018 (für eine Betreffeinheit) oder 114.521-025 (für eine Akte) oder 554.311.01-008 (für eine Akte) oder 512.431-003/002 (für einen Vorgang) oder 554.311.01-008/002 (für einen Vorgang).', regex='^[0-9]{3}\\.[0-9]{1,5}(\\.[0-9]{1,5})?(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3'),
        ),
        migrations.AlterField(
            model_name='originator',
            name='dms_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die <strong><em>d.3</em></strong>-Nummer muss folgendes Format aufweisen (Beispiele): 002.13 (für eine Betreffeinheit) oder 522.13.018 (für eine Betreffeinheit) oder 114.521-025 (für eine Akte) oder 554.311.01-008 (für eine Akte) oder 512.431-003/002 (für einen Vorgang) oder 554.311.01-008/002 (für einen Vorgang).', regex='^[0-9]{3}\\.[0-9]{1,5}(\\.[0-9]{1,5})?(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3'),
        ),
    ]
