# Generated by Django 6.0 on 2025-12-19 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0011_alter_complaint_dms_link_alter_event_dms_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='dms_link_url',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dms_link_url',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='dms_link_url',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='originator',
            name='dms_link_url',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='dms_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die <strong><em>d.3</em></strong>-Nummer muss folgendes Format aufweisen (Beispiele): 002.13 (für eine Betreffeinheit) oder 522.13.018 (für eine Betreffeinheit) oder 114.521-025 (für eine Akte) oder 554.311.01-008 (für eine Akte) oder 512.431-003/002 (für einen Vorgang) oder 554.311.01-008/002 (für einen Vorgang).', regex='^[0-9]{3}\\.[0-9]{1,5}(\\.[0-9]{1,5})?(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3-Nummer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dms_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die <strong><em>d.3</em></strong>-Nummer muss folgendes Format aufweisen (Beispiele): 002.13 (für eine Betreffeinheit) oder 522.13.018 (für eine Betreffeinheit) oder 114.521-025 (für eine Akte) oder 554.311.01-008 (für eine Akte) oder 512.431-003/002 (für einen Vorgang) oder 554.311.01-008/002 (für einen Vorgang).', regex='^[0-9]{3}\\.[0-9]{1,5}(\\.[0-9]{1,5})?(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3-Nummer'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='dms_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die <strong><em>d.3</em></strong>-Nummer muss folgendes Format aufweisen (Beispiele): 002.13 (für eine Betreffeinheit) oder 522.13.018 (für eine Betreffeinheit) oder 114.521-025 (für eine Akte) oder 554.311.01-008 (für eine Akte) oder 512.431-003/002 (für einen Vorgang) oder 554.311.01-008/002 (für einen Vorgang).', regex='^[0-9]{3}\\.[0-9]{1,5}(\\.[0-9]{1,5})?(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3-Nummer'),
        ),
        migrations.AlterField(
            model_name='originator',
            name='dms_link',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die <strong><em>d.3</em></strong>-Nummer muss folgendes Format aufweisen (Beispiele): 002.13 (für eine Betreffeinheit) oder 522.13.018 (für eine Betreffeinheit) oder 114.521-025 (für eine Akte) oder 554.311.01-008 (für eine Akte) oder 512.431-003/002 (für einen Vorgang) oder 554.311.01-008/002 (für einen Vorgang).', regex='^[0-9]{3}\\.[0-9]{1,5}(\\.[0-9]{1,5})?(-[0-9]{3}(\\/[0-9]{3})?)?$')], verbose_name=' d.3-Nummer'),
        ),
    ]
