# Generated by Django 6.1 on 2026-08-20 12:57

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemas', '0012_complaint_dms_link_url_event_dms_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator(message='Die Angabe einer E-Mail-Adresse muss syntaktisch korrekt sein und daher folgendes Format aufweisen (Beispiele): abd@beispiel.de oder vorname.nachname@abc.org')], verbose_name='E-Mail-Adresse(n)'), blank=True, null=True, verbose_name='E-Mail-Adresse(n)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='telephone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die Schreibweise einer Telefonnummer muss der Empfehlung E.123 der Internationalen Fernmeldeunion entsprechen und daher folgendes Format aufweisen (Beispiel): +49 381 3816256', regex='^\\+(1 )?([0-9]{1,3}) [1-9][0-9]{1,5} [0-9]{1,13}$')], verbose_name='Telefonnummer(n)'), blank=True, null=True, verbose_name='Telefonnummer(n)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator(message='Die Angabe einer E-Mail-Adresse muss syntaktisch korrekt sein und daher folgendes Format aufweisen (Beispiele): abd@beispiel.de oder vorname.nachname@abc.org')], verbose_name='E-Mail-Adresse(n)'), blank=True, null=True, verbose_name='E-Mail-Adresse(n)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Die Schreibweise einer Telefonnummer muss der Empfehlung E.123 der Internationalen Fernmeldeunion entsprechen und daher folgendes Format aufweisen (Beispiel): +49 381 3816256', regex='^\\+(1 )?([0-9]{1,3}) [1-9][0-9]{1,5} [0-9]{1,13}$')], verbose_name='Telefonnummer(n)'), blank=True, null=True, verbose_name='Telefonnummer(n)'),
        ),
    ]
