"""
Django settings for datenerfassung project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/


# Application definition

DATENMANAGEMENT_VERSION = '4.6.0'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
]

LOCAL_APPS = [
    'datenmanagement',
]

THIRD_PARTY_APPS = [
    'django_user_agents',
    'guardian',
    'leaflet',
    'requests',
    'rest_framework',
    'tempus_dominus',
    'jsonview'
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',
]

ROOT_URLCONF = 'datenerfassung.urls'

WSGI_APPLICATION = 'datenerfassung.wsgi.application'


# Security

CSRF_COOKIE_SECURE = False

SECURE_BROWSER_XSS_FILTER = True

SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = 'DENY'


# Leaflet

LEAFLET_CONFIG = {
    'SPATIAL_EXTENT': (10.53001, 52.98541, 14.68873, 54.82175),
    'DEFAULT_CENTER': (54.14775, 12.14945),
    'DEFAULT_ZOOM': 11,
    'MIN_ZOOM': 11,
    'MAX_ZOOM': 19,
    'TILES': [],
    'SRID': 3857,
    'ATTRIBUTION_PREFIX': '',
    'RESET_VIEW': False,
    'PLUGINS': {
        'forms': {
            'auto_include': True
        },
        'geoman': {
            'css': ['leaflet-geoman-2.11.4/leaflet-geoman.css'],
            'js': ['leaflet-geoman-2.11.4/leaflet-geoman.min.js'],
            'auto_include': True
        }
    }
}


# REST framework

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],
    'DATETIME_FORMAT': 'iso-8601',
    'DATE_FORMAT': 'iso-8601',
    'TIME_FORMAT': 'iso-8601',
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}


# Tempus Dominus

TEMPUS_DOMINUS_LOCALIZE = True


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Link auf Konfigurationsdatei mit weiteren Parametern,
# die nicht unter Git-Versionskontrolle fallen sollen

try:
    from datenerfassung.secrets import *
except ImportError:
    pass
