@startuml
skinparam linetype ortho

package antragsmanagement {
  class buttons_form_request_followup {}
  class container_errors {}
  class container_messages {}
  class container_table_warnings {}

  class anonymous_map {
    {field} title
    {field} style
    {field} scripts
    {field} content
    {method} extend style
    {method} extend scripts
  }

  class decision {
    {field} title
    {field} content
    {method} include container_messages
    {method} include container_errors
    {method} include notice_no_request
    {method} include notice_no_permissions
  }

  class delete {
    {field} title
    {field} content
    {method} include container_errors
    {method} include notice_no_permissions
  }

  class form_request {
    {field} title
    {field} style
    {field} scripts
    {field} content
    {method} extend style
    {method} extend scripts
    {method} include container_errors
    {method} include notice_no_contact_data
    {method} include notice_no_permissions
  }

  class form_request_followup {
    {field} title
    {field} style
    {field} scripts
    {field} content
    {method} extend style
    {method} extend scripts
    {method} include buttons_form_request_followup
    {method} include container_messages
    {method} include container_errors
    {method} include notice_no_request
    {method} include notice_no_permissions
  }

  class form_simple {
    {field} title
    {field} style
    {field} scripts
    {field} content
    {method} extend style
    {method} extend scripts
    {method} include container_errors
    {method} include notice_no_permissions
  }

  class index {
    {field} title
    {field} content
    {method} include container_messages
    {method} include notice_no_permissions
  }

  class map_filters_cleanupeventrequest {}

  class map_request {
    {field} title
    {field} style
    {field} scripts
    {field} content
    {method} extend style
    {method} extend scripts
    {method} include container_messages
    {method} include map_filters_cleanupeventrequest
    {method} include notice_no_permissions
  }

  class notice_no_contact_data {}
  class notice_no_permissions {}
  class notice_no_request {}

  class table_request {
    {field} title
    {field} style
    {field} scripts
    {field} content
    {method} extend style
    {method} extend scripts
    {method} include container_messages
    {method} include container_table_warning
    {method} include notice_no_permissions
  }

  class table_simple {
    {field} title
    {field} style
    {field} scripts
    {field} content
    {method} extend style
    {method} extend scripts
    {method} include container_messages
    {method} include container_table_warning
    {method} include notice_no_permissions
  }
}

datenwerft.base <|-- antragsmanagement.anonymous_map
datenwerft.base <|-- antragsmanagement.decision
datenwerft.base <|-- antragsmanagement.delete
datenwerft.base <|-- antragsmanagement.form_request
datenwerft.base <|-- antragsmanagement.form_request_followup
datenwerft.base <|-- antragsmanagement.form_simple
datenwerft.base <|-- antragsmanagement.index
datenwerft.base <|-- antragsmanagement.map_request
datenwerft.base <|-- antragsmanagement.table_request
datenwerft.base <|-- antragsmanagement.table_simple


antragsmanagement.decision ..> antragsmanagement.container_messages
antragsmanagement.decision ..> antragsmanagement.container_errors
antragsmanagement.decision ..> antragsmanagement.notice_no_request
antragsmanagement.decision ..> antragsmanagement.notice_no_permissions
antragsmanagement.delete ..> antragsmanagement.container_errors
antragsmanagement.delete ..> antragsmanagement.notice_no_permissions
antragsmanagement.form_request ..> antragsmanagement.container_errors
antragsmanagement.form_request ..> antragsmanagement.notice_no_contact_data
antragsmanagement.form_request ..> antragsmanagement.notice_no_permissions
antragsmanagement.form_request_followup ..> antragsmanagement.buttons_form_request_followup
antragsmanagement.form_request_followup ..> antragsmanagement.container_messages
antragsmanagement.form_request_followup ..> antragsmanagement.container_errors
antragsmanagement.form_request_followup ..> antragsmanagement.notice_no_request
antragsmanagement.form_request_followup ..> antragsmanagement.notice_no_permissions
antragsmanagement.form_simple ..> antragsmanagement.container_errors
antragsmanagement.form_simple ..> antragsmanagement.notice_no_permissions
antragsmanagement.index ..> antragsmanagement.container_messages
antragsmanagement.index ..> antragsmanagement.notice_no_permissions
antragsmanagement.map_request ..> antragsmanagement.map_filters_cleanupeventrequest
antragsmanagement.map_request ..> antragsmanagement.notice_no_permissions
antragsmanagement.table_request ..> antragsmanagement.container_messages
antragsmanagement.table_request ..> antragsmanagement.container_table_warning
antragsmanagement.table_request ..> antragsmanagement.notice_no_permissions
antragsmanagement.table_simple ..> antragsmanagement.container_messages
antragsmanagement.table_simple ..> antragsmanagement.container_table_warning
antragsmanagement.table_simple ..> antragsmanagement.notice_no_permissions

@enduml