@startuml
skinparam linetype ortho

package datenwerft{
  abstract base {
    {field} head
    {field} meta
    {field} title
    {field} style
    {field} scripts
    {field} navbar
    {field} content
    {field} footer
    {method} include navbar_html
  }

  class navbar_html {
    {field} navbar
  }

  class index {
    {field} title
    {field} content
  }

  class error {
    {field} title
    {field} content
  }

  class modal_confirm_export {}
  class modal_error {}
  class modal_loading {}
}


datenwerft.base ..> datenwerft.navbar_html
datenwerft.base <|-- datenwerft.index
datenwerft.base <|-- datenwerft.error


@enduml